import {
  ClientType,
  FieldType,
  FormMetadata,
  FormModule,
  FormPermission,
  ValidationRuleType,
} from "../types";
import { formRegistry } from "../registry";

/**
 * Committee Decision Form (F05.3)
 * Used for recording committee decisions, approvals, and comments
 */
export const committeeDecisionForm: FormMetadata = {
  id: "committee-decision-form",
  title: "Committee Decision",
  description: "Record committee decisions, approvals, and comments",
  module: FormModule.COMMITTEE,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: ["admin", "manager", "committee-member"],
    [FormPermission.CREATE]: ["admin", "manager", "committee-member"],
    [FormPermission.EDIT]: ["admin", "manager"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["admin", "manager"],
    [FormPermission.REJECT]: ["admin", "manager"],
    [FormPermission.SUBMIT]: ["admin", "manager", "committee-member"],
    [FormPermission.PRINT]: ["admin", "manager", "committee-member"],
    [FormPermission.EXPORT]: ["admin", "manager"],
  },
  clientTypes: [
    ClientType.FDF,
    ClientType.ADHA,
    ClientType.CASH,
    ClientType.OTHER,
  ],
  sections: [
    {
      id: "committee-info",
      title: "Committee Information",
      description: "Information about the committee",
      order: 1,
      collapsible: false,
    },
    {
      id: "submission-details",
      title: "Submission Details",
      description: "Details of the submission being reviewed",
      order: 2,
      collapsible: false,
    },
    {
      id: "decision-details",
      title: "Decision Details",
      description: "Details of the committee decision",
      order: 3,
      collapsible: false,
    },
    {
      id: "voting-record",
      title: "Voting Record",
      description: "Record of committee member votes",
      order: 4,
      collapsible: true,
    },
    {
      id: "conditions-recommendations",
      title: "Conditions & Recommendations",
      description: "Any conditions or recommendations for approval",
      order: 5,
      collapsible: true,
    },
    {
      id: "documentation",
      title: "Documentation",
      description: "Supporting documentation for the decision",
      order: 6,
      collapsible: true,
    },
  ],
  fields: [
    {
      id: "committee-id",
      name: "committeeId",
      label: "Committee",
      type: FieldType.SELECT,
      required: true,
      section: "committee-info",
      order: 1,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/committees/list",
        valueField: "id",
        labelField: "name",
        filters: { active: true },
      },
    },
    {
      id: "meeting-id",
      name: "meetingId",
      label: "Meeting Reference",
      type: FieldType.SELECT,
      required: true,
      section: "committee-info",
      order: 2,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/committees/{committeeId}/meetings",
        valueField: "id",
        labelField: "title",
        filters: { status: "scheduled" },
        dependsOn: ["committeeId"],
      },
      dependencies: [
        {
          type: "visibility",
          sourceField: "committeeId",
          condition: "!!value",
          action: "visible = true",
        },
      ],
    },
    {
      id: "meeting-date",
      name: "meetingDate",
      label: "Meeting Date",
      type: FieldType.DATE,
      required: true,
      section: "committee-info",
      order: 3,
      width: "half",
      readOnly: true,
      dataSource: {
        type: "api",
        source: "/api/committees/meetings/{meetingId}/details",
        valueField: "meetingDate",
        labelField: "meetingDate",
        dependsOn: ["meetingId"],
      },
    },
    {
      id: "chairperson",
      name: "chairperson",
      label: "Chairperson",
      type: FieldType.TEXT,
      required: true,
      section: "committee-info",
      order: 4,
      width: "half",
      readOnly: true,
      dataSource: {
        type: "api",
        source: "/api/committees/{committeeId}/chairperson",
        valueField: "name",
        labelField: "name",
        dependsOn: ["committeeId"],
      },
    },
    {
      id: "submission-type",
      name: "submissionType",
      label: "Submission Type",
      type: FieldType.SELECT,
      required: true,
      section: "submission-details",
      order: 1,
      width: "half",
      options: [
        { value: "project-approval", label: "Project Approval" },
        { value: "budget-approval", label: "Budget Approval" },
        { value: "beneficiary-approval", label: "Beneficiary Approval" },
        { value: "procurement-approval", label: "Procurement Approval" },
        { value: "change-request", label: "Change Request" },
        { value: "other", label: "Other" },
      ],
    },
    {
      id: "submission-id",
      name: "submissionId",
      label: "Submission Reference",
      type: FieldType.SELECT,
      required: true,
      section: "submission-details",
      order: 2,
      width: "half",
      dataSource: {
        type: "api",
        source: "/api/submissions/list",
        valueField: "id",
        labelField: "title",
        filters: { type: "{submissionType}", status: "pending" },
        dependsOn: ["submissionType"],
      },
      dependencies: [
        {
          type: "visibility",
          sourceField: "submissionType",
          condition: "!!value",
          action: "visible = true",
        },
      ],
    },
    {
      id: "submission-title",
      name: "submissionTitle",
      label: "Submission Title",
      type: FieldType.TEXT,
      required: true,
      section: "submission-details",
      order: 3,
      width: "full",
      readOnly: true,
      dataSource: {
        type: "api",
        source: "/api/submissions/{submissionId}/details",
        valueField: "title",
        labelField: "title",
        dependsOn: ["submissionId"],
      },
    },
    {
      id: "submission-description",
      name: "submissionDescription",
      label: "Submission Description",
      type: FieldType.TEXTAREA,
      required: false,
      section: "submission-details",
      order: 4,
      width: "full",
      readOnly: true,
      dataSource: {
        type: "api",
        source: "/api/submissions/{submissionId}/details",
        valueField: "description",
        labelField: "description",
        dependsOn: ["submissionId"],
      },
    },
    {
      id: "decision",
      name: "decision",
      label: "Decision",
      type: FieldType.SELECT,
      required: true,
      section: "decision-details",
      order: 1,
      width: "half",
      options: [
        { value: "approved", label: "Approved" },
        {
          value: "approved-with-conditions",
          label: "Approved with Conditions",
        },
        { value: "deferred", label: "Deferred" },
        { value: "rejected", label: "Rejected" },
        {
          value: "more-information-required",
          label: "More Information Required",
        },
      ],
    },
    {
      id: "decision-date",
      name: "decisionDate",
      label: "Decision Date",
      type: FieldType.DATE,
      required: true,
      section: "decision-details",
      order: 2,
      width: "half",
      defaultValue: new Date().toISOString().split("T")[0],
    },
    {
      id: "decision-rationale",
      name: "decisionRationale",
      label: "Decision Rationale",
      type: FieldType.TEXTAREA,
      required: true,
      section: "decision-details",
      order: 3,
      width: "full",
      placeholder: "Provide detailed rationale for the decision",
    },
    {
      id: "voting-members",
      name: "votingMembers",
      label: "Voting Members",
      type: FieldType.REPEATER,
      required: true,
      section: "voting-record",
      order: 1,
      width: "full",
      fields: [
        {
          id: "member-name",
          name: "memberName",
          label: "Member Name",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "member-role",
          name: "memberRole",
          label: "Role",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "vote",
          name: "vote",
          label: "Vote",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "approve", label: "Approve" },
            { value: "reject", label: "Reject" },
            { value: "abstain", label: "Abstain" },
            { value: "absent", label: "Absent" },
          ],
        },
      ],
    },
    {
      id: "vote-summary",
      name: "voteSummary",
      label: "Vote Summary",
      type: FieldType.TEXTAREA,
      required: true,
      section: "voting-record",
      order: 2,
      width: "full",
      placeholder: "Summarize the voting results",
    },
    {
      id: "conditions",
      name: "conditions",
      label: "Conditions for Approval",
      type: FieldType.REPEATER,
      required: false,
      section: "conditions-recommendations",
      order: 1,
      width: "full",
      dependencies: [
        {
          type: "visibility",
          sourceField: "decision",
          condition: "value === 'approved-with-conditions'",
          action: "visible = true",
        },
        {
          type: "requirement",
          sourceField: "decision",
          condition: "value === 'approved-with-conditions'",
          action: "required = true",
        },
      ],
      fields: [
        {
          id: "condition-description",
          name: "conditionDescription",
          label: "Condition",
          type: FieldType.TEXT,
          required: true,
          width: "half",
        },
        {
          id: "condition-deadline",
          name: "conditionDeadline",
          label: "Deadline",
          type: FieldType.DATE,
          required: true,
          width: "half",
        },
      ],
    },
    {
      id: "recommendations",
      name: "recommendations",
      label: "Recommendations",
      type: FieldType.TEXTAREA,
      required: false,
      section: "conditions-recommendations",
      order: 2,
      width: "full",
      placeholder: "Enter any recommendations or suggestions",
    },
    {
      id: "next-steps",
      name: "nextSteps",
      label: "Next Steps",
      type: FieldType.TEXTAREA,
      required: true,
      section: "conditions-recommendations",
      order: 3,
      width: "full",
      placeholder: "Outline the next steps following this decision",
    },
    {
      id: "supporting-documents",
      name: "supportingDocuments",
      label: "Supporting Documents",
      type: FieldType.FILE,
      required: false,
      section: "documentation",
      order: 1,
      width: "full",
      multiple: true,
      helpText: "Upload any supporting documents for the decision",
    },
    {
      id: "chairperson-signature",
      name: "chairpersonSignature",
      label: "Chairperson Signature",
      type: FieldType.SIGNATURE,
      required: true,
      section: "documentation",
      order: 2,
      width: "full",
    },
    {
      id: "secretary-signature",
      name: "secretarySignature",
      label: "Secretary Signature",
      type: FieldType.SIGNATURE,
      required: true,
      section: "documentation",
      order: 3,
      width: "full",
    },
  ],
  dependencies: [
    {
      formId: "committee-meeting-form",
      description: "Committee decision requires a scheduled meeting",
      type: "prerequisite",
      required: true,
    },
  ],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

// Register form with the form registry
formRegistry.registerForm(
  {
    id: committeeDecisionForm.id,
    title: committeeDecisionForm.title,
    description: committeeDecisionForm.description,
    module: committeeDecisionForm.module,
    clientTypes: committeeDecisionForm.clientTypes,
    permissions: committeeDecisionForm.permissions,
    dependencies: committeeDecisionForm.dependencies,
    version: committeeDecisionForm.version,
    path: "/committee/decisions",
    icon: "check-circle",
    isActive: true,
  },
  committeeDecisionForm,
);
