import {
  ClientType,
  FieldType,
  FormMetadata,
  FormModule,
  FormPermission,
  ValidationRuleType,
} from "../types";
import { formRegistry } from "../registry";

/**
 * Committee Meeting Form
 * Used for scheduling and documenting committee meetings
 */
export const committeeMeetingForm: FormMetadata = {
  id: "committee-meeting-form",
  title: "Committee Meeting",
  description: "Schedule and document committee meetings",
  module: FormModule.COMMITTEE,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: ["admin", "manager", "committee-member"],
    [FormPermission.CREATE]: ["admin", "manager"],
    [FormPermission.EDIT]: ["admin", "manager"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["admin"],
    [FormPermission.REJECT]: ["admin"],
    [FormPermission.SUBMIT]: ["admin", "manager"],
    [FormPermission.PRINT]: ["admin", "manager", "committee-member"],
    [FormPermission.EXPORT]: ["admin", "manager"],
  },
  clientTypes: [
    ClientType.FDF,
    ClientType.ADHA,
    ClientType.CASH,
    ClientType.OTHER,
  ],
  sections: [
    {
      id: "meeting-details",
      title: "Meeting Details",
      description: "Basic information about the committee meeting",
      order: 1,
      collapsible: false,
    },
    {
      id: "agenda",
      title: "Agenda",
      description: "Meeting agenda items",
      order: 2,
      collapsible: false,
    },
    {
      id: "attendees",
      title: "Attendees",
      description: "Committee members and other attendees",
      order: 3,
      collapsible: true,
    },
    {
      id: "documents",
      title: "Documents",
      description: "Meeting documents and attachments",
      order: 4,
      collapsible: true,
    },
  ],
  fields: [
    {
      id: "meeting-title",
      name: "meetingTitle",
      label: "Meeting Title",
      type: FieldType.TEXT,
      placeholder: "Enter meeting title",
      required: true,
      section: "meeting-details",
      order: 1,
      width: "full",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Meeting title is required",
        },
      ],
    },
    {
      id: "committee-type",
      name: "committeeType",
      label: "Committee Type",
      type: FieldType.SELECT,
      required: true,
      section: "meeting-details",
      order: 2,
      width: "half",
      options: [
        { value: "approval", label: "Approval Committee" },
        { value: "technical", label: "Technical Committee" },
        { value: "financial", label: "Financial Committee" },
        { value: "executive", label: "Executive Committee" },
        { value: "other", label: "Other" },
      ],
    },
    {
      id: "meeting-date",
      name: "meetingDate",
      label: "Meeting Date",
      type: FieldType.DATE,
      required: true,
      section: "meeting-details",
      order: 3,
      width: "half",
    },
    {
      id: "meeting-time",
      name: "meetingTime",
      label: "Meeting Time",
      type: FieldType.TIME,
      required: true,
      section: "meeting-details",
      order: 4,
      width: "half",
    },
    {
      id: "meeting-location",
      name: "meetingLocation",
      label: "Meeting Location",
      type: FieldType.TEXT,
      placeholder: "Enter meeting location",
      required: true,
      section: "meeting-details",
      order: 5,
      width: "half",
    },
    {
      id: "meeting-duration",
      name: "meetingDuration",
      label: "Duration (minutes)",
      type: FieldType.NUMBER,
      required: true,
      section: "meeting-details",
      order: 6,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.MIN_VALUE,
          value: 15,
          message: "Duration must be at least 15 minutes",
        },
      ],
    },
    {
      id: "agenda-items",
      name: "agendaItems",
      label: "Agenda Items",
      type: FieldType.REPEATER,
      required: true,
      section: "agenda",
      order: 1,
      width: "full",
      fields: [
        {
          id: "item-title",
          name: "itemTitle",
          label: "Item Title",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "item-duration",
          name: "itemDuration",
          label: "Duration (min)",
          type: FieldType.NUMBER,
          required: true,
          width: "third",
        },
        {
          id: "item-presenter",
          name: "itemPresenter",
          label: "Presenter",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
      ],
    },
    {
      id: "agenda-notes",
      name: "agendaNotes",
      label: "Additional Agenda Notes",
      type: FieldType.TEXTAREA,
      placeholder: "Enter any additional notes about the agenda",
      required: false,
      section: "agenda",
      order: 2,
      width: "full",
    },
    {
      id: "committee-members",
      name: "committeeMembers",
      label: "Committee Members",
      type: FieldType.REPEATER,
      required: true,
      section: "attendees",
      order: 1,
      width: "full",
      fields: [
        {
          id: "member-name",
          name: "memberName",
          label: "Name",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "member-role",
          name: "memberRole",
          label: "Role",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "attendance-status",
          name: "attendanceStatus",
          label: "Attendance",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "attending", label: "Attending" },
            { value: "tentative", label: "Tentative" },
            { value: "not-attending", label: "Not Attending" },
            { value: "no-response", label: "No Response" },
          ],
        },
      ],
    },
    {
      id: "other-attendees",
      name: "otherAttendees",
      label: "Other Attendees",
      type: FieldType.REPEATER,
      required: false,
      section: "attendees",
      order: 2,
      width: "full",
      fields: [
        {
          id: "attendee-name",
          name: "attendeeName",
          label: "Name",
          type: FieldType.TEXT,
          required: true,
          width: "half",
        },
        {
          id: "attendee-organization",
          name: "attendeeOrganization",
          label: "Organization",
          type: FieldType.TEXT,
          required: true,
          width: "half",
        },
      ],
    },
    {
      id: "meeting-agenda-doc",
      name: "meetingAgendaDoc",
      label: "Meeting Agenda Document",
      type: FieldType.FILE,
      helpText:
        "Upload the detailed meeting agenda document (PDF format preferred)",
      required: false,
      section: "documents",
      order: 1,
      width: "full",
    },
    {
      id: "supporting-documents",
      name: "supportingDocuments",
      label: "Supporting Documents",
      type: FieldType.FILE,
      helpText: "Upload any supporting documents for the meeting",
      required: false,
      section: "documents",
      order: 2,
      width: "full",
      multiple: true,
    },
  ],
  dependencies: [],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

/**
 * Committee Decision Form
 * Used for recording committee decisions
 */
export const committeeDecisionForm: FormMetadata = {
  id: "committee-decision-form",
  title: "Committee Decision",
  description: "Record committee decisions and outcomes",
  module: FormModule.COMMITTEE,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: ["admin", "manager", "committee-member"],
    [FormPermission.CREATE]: ["admin", "manager"],
    [FormPermission.EDIT]: ["admin", "manager"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["admin"],
    [FormPermission.REJECT]: ["admin"],
    [FormPermission.SUBMIT]: ["admin", "manager"],
    [FormPermission.PRINT]: ["admin", "manager", "committee-member"],
    [FormPermission.EXPORT]: ["admin", "manager"],
  },
  clientTypes: [
    ClientType.FDF,
    ClientType.ADHA,
    ClientType.CASH,
    ClientType.OTHER,
  ],
  sections: [
    {
      id: "meeting-reference",
      title: "Meeting Reference",
      description: "Reference to the committee meeting",
      order: 1,
      collapsible: false,
    },
    {
      id: "decision-details",
      title: "Decision Details",
      description: "Details of the committee decision",
      order: 2,
      collapsible: false,
    },
    {
      id: "voting",
      title: "Voting Record",
      description: "Record of committee member votes",
      order: 3,
      collapsible: true,
    },
    {
      id: "follow-up",
      title: "Follow-up Actions",
      description: "Actions to be taken based on the decision",
      order: 4,
      collapsible: true,
    },
  ],
  fields: [
    {
      id: "meeting-id",
      name: "meetingId",
      label: "Committee Meeting",
      type: FieldType.SELECT,
      required: true,
      section: "meeting-reference",
      order: 1,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/committee/meetings",
        valueField: "id",
        labelField: "title",
        filters: { status: "active" },
      },
    },
    {
      id: "agenda-item-id",
      name: "agendaItemId",
      label: "Agenda Item",
      type: FieldType.SELECT,
      required: true,
      section: "meeting-reference",
      order: 2,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/committee/meetings/{meetingId}/agenda-items",
        valueField: "id",
        labelField: "title",
        dependsOn: ["meetingId"],
      },
      dependencies: [
        {
          type: "visibility",
          sourceField: "meetingId",
          condition: "!!value",
          action: "visible = true",
        },
      ],
    },
    {
      id: "decision-title",
      name: "decisionTitle",
      label: "Decision Title",
      type: FieldType.TEXT,
      placeholder: "Enter a title for this decision",
      required: true,
      section: "decision-details",
      order: 1,
      width: "full",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Decision title is required",
        },
      ],
    },
    {
      id: "decision-type",
      name: "decisionType",
      label: "Decision Type",
      type: FieldType.SELECT,
      required: true,
      section: "decision-details",
      order: 2,
      width: "half",
      options: [
        { value: "approval", label: "Approval" },
        { value: "rejection", label: "Rejection" },
        { value: "deferral", label: "Deferral" },
        { value: "modification", label: "Approval with Modifications" },
        { value: "information", label: "Information Only" },
      ],
    },
    {
      id: "decision-date",
      name: "decisionDate",
      label: "Decision Date",
      type: FieldType.DATE,
      required: true,
      section: "decision-details",
      order: 3,
      width: "half",
      defaultValue: new Date().toISOString().split("T")[0],
    },
    {
      id: "decision-description",
      name: "decisionDescription",
      label: "Decision Description",
      type: FieldType.TEXTAREA,
      placeholder: "Enter detailed description of the decision",
      required: true,
      section: "decision-details",
      order: 4,
      width: "full",
    },
    {
      id: "decision-rationale",
      name: "decisionRationale",
      label: "Decision Rationale",
      type: FieldType.TEXTAREA,
      placeholder: "Explain the rationale behind this decision",
      required: true,
      section: "decision-details",
      order: 5,
      width: "full",
    },
    {
      id: "voting-record",
      name: "votingRecord",
      label: "Voting Record",
      type: FieldType.REPEATER,
      required: true,
      section: "voting",
      order: 1,
      width: "full",
      fields: [
        {
          id: "member-name",
          name: "memberName",
          label: "Member Name",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "vote",
          name: "vote",
          label: "Vote",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "approve", label: "Approve" },
            { value: "reject", label: "Reject" },
            { value: "abstain", label: "Abstain" },
            { value: "absent", label: "Absent" },
          ],
        },
        {
          id: "comments",
          name: "comments",
          label: "Comments",
          type: FieldType.TEXT,
          required: false,
          width: "third",
        },
      ],
    },
    {
      id: "voting-summary",
      name: "votingSummary",
      label: "Voting Summary",
      type: FieldType.TEXTAREA,
      placeholder: "Summarize the voting results",
      required: false,
      section: "voting",
      order: 2,
      width: "full",
    },
    {
      id: "follow-up-actions",
      name: "followUpActions",
      label: "Follow-up Actions",
      type: FieldType.REPEATER,
      required: false,
      section: "follow-up",
      order: 1,
      width: "full",
      fields: [
        {
          id: "action-description",
          name: "actionDescription",
          label: "Action Description",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "responsible-person",
          name: "responsiblePerson",
          label: "Responsible Person",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "due-date",
          name: "dueDate",
          label: "Due Date",
          type: FieldType.DATE,
          required: true,
          width: "third",
        },
      ],
    },
    {
      id: "decision-document",
      name: "decisionDocument",
      label: "Decision Document",
      type: FieldType.FILE,
      helpText: "Upload the official decision document if available",
      required: false,
      section: "follow-up",
      order: 2,
      width: "full",
    },
  ],
  dependencies: [
    {
      formId: "committee-meeting-form",
      description: "Decision must be linked to a committee meeting",
      type: "prerequisite",
      required: true,
    },
  ],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

/**
 * Committee Member Assignment Form
 * Used for assigning members to committees
 */
export const committeeMemberAssignmentForm: FormMetadata = {
  id: "committee-member-assignment-form",
  title: "Committee Member Assignment",
  description: "Assign members to committees and define their roles",
  module: FormModule.COMMITTEE,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: ["admin", "manager"],
    [FormPermission.CREATE]: ["admin", "manager"],
    [FormPermission.EDIT]: ["admin", "manager"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["admin"],
    [FormPermission.REJECT]: ["admin"],
    [FormPermission.SUBMIT]: ["admin", "manager"],
    [FormPermission.PRINT]: ["admin", "manager"],
    [FormPermission.EXPORT]: ["admin", "manager"],
  },
  clientTypes: [
    ClientType.FDF,
    ClientType.ADHA,
    ClientType.CASH,
    ClientType.OTHER,
  ],
  sections: [
    {
      id: "committee-info",
      title: "Committee Information",
      description: "Basic information about the committee",
      order: 1,
      collapsible: false,
    },
    {
      id: "member-assignments",
      title: "Member Assignments",
      description: "Assign members to the committee",
      order: 2,
      collapsible: false,
    },
    {
      id: "term-details",
      title: "Term Details",
      description: "Details about the committee term",
      order: 3,
      collapsible: true,
    },
  ],
  fields: [
    {
      id: "committee-name",
      name: "committeeName",
      label: "Committee Name",
      type: FieldType.TEXT,
      placeholder: "Enter committee name",
      required: true,
      section: "committee-info",
      order: 1,
      width: "full",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Committee name is required",
        },
      ],
    },
    {
      id: "committee-type",
      name: "committeeType",
      label: "Committee Type",
      type: FieldType.SELECT,
      required: true,
      section: "committee-info",
      order: 2,
      width: "half",
      options: [
        { value: "approval", label: "Approval Committee" },
        { value: "technical", label: "Technical Committee" },
        { value: "financial", label: "Financial Committee" },
        { value: "executive", label: "Executive Committee" },
        { value: "other", label: "Other" },
      ],
    },
    {
      id: "committee-purpose",
      name: "committeePurpose",
      label: "Committee Purpose",
      type: FieldType.TEXTAREA,
      placeholder: "Describe the purpose of this committee",
      required: true,
      section: "committee-info",
      order: 3,
      width: "full",
    },
    {
      id: "member-assignments",
      name: "memberAssignments",
      label: "Member Assignments",
      type: FieldType.REPEATER,
      required: true,
      section: "member-assignments",
      order: 1,
      width: "full",
      fields: [
        {
          id: "member-id",
          name: "memberId",
          label: "Member",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          dataSource: {
            type: "api",
            source: "/api/users",
            valueField: "id",
            labelField: "fullName",
            filters: { active: true },
          },
        },
        {
          id: "role",
          name: "role",
          label: "Role",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "chairperson", label: "Chairperson" },
            { value: "secretary", label: "Secretary" },
            { value: "member", label: "Member" },
            { value: "advisor", label: "Advisor" },
            { value: "observer", label: "Observer" },
          ],
        },
        {
          id: "voting-rights",
          name: "votingRights",
          label: "Voting Rights",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "full", label: "Full Voting Rights" },
            { value: "limited", label: "Limited Voting Rights" },
            { value: "none", label: "No Voting Rights" },
          ],
        },
      ],
    },
    {
      id: "term-start-date",
      name: "termStartDate",
      label: "Term Start Date",
      type: FieldType.DATE,
      required: true,
      section: "term-details",
      order: 1,
      width: "half",
    },
    {
      id: "term-end-date",
      name: "termEndDate",
      label: "Term End Date",
      type: FieldType.DATE,
      required: true,
      section: "term-details",
      order: 2,
      width: "half",
      dependencies: [
        {
          type: "validation",
          sourceField: "termStartDate",
          condition:
            "value && sourceValue && new Date(value) <= new Date(sourceValue)",
          action: "return 'End date must be after start date'",
        },
      ],
    },
    {
      id: "meeting-frequency",
      name: "meetingFrequency",
      label: "Meeting Frequency",
      type: FieldType.SELECT,
      required: true,
      section: "term-details",
      order: 3,
      width: "half",
      options: [
        { value: "weekly", label: "Weekly" },
        { value: "biweekly", label: "Bi-weekly" },
        { value: "monthly", label: "Monthly" },
        { value: "quarterly", label: "Quarterly" },
        { value: "asNeeded", label: "As Needed" },
      ],
    },
    {
      id: "quorum-requirement",
      name: "quorumRequirement",
      label: "Quorum Requirement",
      type: FieldType.TEXT,
      placeholder: "e.g., 'Simple majority', '2/3 of members'",
      required: true,
      section: "term-details",
      order: 4,
      width: "half",
    },
    {
      id: "additional-notes",
      name: "additionalNotes",
      label: "Additional Notes",
      type: FieldType.TEXTAREA,
      placeholder: "Enter any additional notes about the committee",
      required: false,
      section: "term-details",
      order: 5,
      width: "full",
    },
  ],
  dependencies: [],
  submitEndpoint: "/api/committee/members",
  fetchDataEndpoint: "/api/committee/members/{id}",
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

// Register forms with the form registry
formRegistry.registerForm(
  {
    id: committeeMeetingForm.id,
    title: committeeMeetingForm.title,
    description: committeeMeetingForm.description,
    module: committeeMeetingForm.module,
    clientTypes: committeeMeetingForm.clientTypes,
    permissions: committeeMeetingForm.permissions,
    dependencies: committeeMeetingForm.dependencies,
    version: committeeMeetingForm.version,
    path: "/committee/meetings",
    icon: "users",
    isActive: true,
  },
  committeeMeetingForm,
);

formRegistry.registerForm(
  {
    id: committeeDecisionForm.id,
    title: committeeDecisionForm.title,
    description: committeeDecisionForm.description,
    module: committeeDecisionForm.module,
    clientTypes: committeeDecisionForm.clientTypes,
    permissions: committeeDecisionForm.permissions,
    dependencies: committeeDecisionForm.dependencies,
    version: committeeDecisionForm.version,
    path: "/committee/decisions",
    icon: "check-square",
    isActive: true,
  },
  committeeDecisionForm,
);

formRegistry.registerForm(
  {
    id: committeeMemberAssignmentForm.id,
    title: committeeMemberAssignmentForm.title,
    description: committeeMemberAssignmentForm.description,
    module: committeeMemberAssignmentForm.module,
    clientTypes: committeeMemberAssignmentForm.clientTypes,
    permissions: committeeMemberAssignmentForm.permissions,
    dependencies: committeeMemberAssignmentForm.dependencies,
    version: committeeMemberAssignmentForm.version,
    path: "/committee/members",
    icon: "user-plus",
    isActive: true,
  },
  committeeMemberAssignmentForm,
);
