import {
  ClientType,
  FieldType,
  FormMetadata,
  FormModule,
  FormPermission,
  ValidationRuleType,
} from "../types";
import { formRegistry } from "../registry";

/**
 * Drawing Approval Form (F12.2)
 * Used to document the approval process for architectural and modification drawings
 */
export const drawingApproval: FormMetadata = {
  id: "drawing-approval-form",
  title: "Drawing Approval",
  description:
    "Document the approval process for architectural and modification drawings",
  module: FormModule.DRAWING,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: [
      "admin",
      "manager",
      "architect",
      "engineer",
      "inspector",
    ],
    [FormPermission.CREATE]: ["admin", "manager", "architect"],
    [FormPermission.EDIT]: ["admin", "manager", "architect"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["admin", "manager", "engineer"],
    [FormPermission.REJECT]: ["admin", "manager", "engineer"],
    [FormPermission.SUBMIT]: ["admin", "manager", "architect"],
    [FormPermission.PRINT]: [
      "admin",
      "manager",
      "architect",
      "engineer",
      "inspector",
    ],
    [FormPermission.EXPORT]: ["admin", "manager"],
  },
  clientTypes: [
    ClientType.FDF,
    ClientType.ADHA,
    ClientType.CASH,
    ClientType.OTHER,
  ],
  sections: [
    {
      id: "drawing-information",
      title: "Drawing Information",
      description: "Basic information about the drawing",
      order: 1,
      collapsible: false,
    },
    {
      id: "project-details",
      title: "Project Details",
      description: "Information about the associated project",
      order: 2,
      collapsible: false,
    },
    {
      id: "drawing-details",
      title: "Drawing Details",
      description: "Specific details about the drawing",
      order: 3,
      collapsible: false,
    },
    {
      id: "review-comments",
      title: "Review Comments",
      description: "Comments from reviewers",
      order: 4,
      collapsible: true,
    },
    {
      id: "approval-details",
      title: "Approval Details",
      description: "Information about the approval decision",
      order: 5,
      collapsible: false,
    },
  ],
  fields: [
    {
      id: "drawing-id",
      name: "drawingId",
      label: "Drawing ID",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "drawing-information",
      order: 1,
      width: "half",
      helpText: "Unique identifier for the drawing",
    },
    {
      id: "drawing-title",
      name: "drawingTitle",
      label: "Drawing Title",
      type: FieldType.TEXT,
      required: true,
      section: "drawing-information",
      order: 2,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Drawing title is required",
        },
      ],
    },
    {
      id: "drawing-type",
      name: "drawingType",
      label: "Drawing Type",
      type: FieldType.SELECT,
      required: true,
      section: "drawing-information",
      order: 3,
      width: "half",
      options: [
        { value: "architectural", label: "Architectural" },
        { value: "structural", label: "Structural" },
        { value: "electrical", label: "Electrical" },
        { value: "plumbing", label: "Plumbing" },
        { value: "mechanical", label: "Mechanical" },
        { value: "interior", label: "Interior Design" },
        { value: "site-plan", label: "Site Plan" },
        { value: "other", label: "Other" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Drawing type is required",
        },
      ],
    },
    {
      id: "drawing-version",
      name: "drawingVersion",
      label: "Version",
      type: FieldType.TEXT,
      required: true,
      section: "drawing-information",
      order: 4,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Drawing version is required",
        },
      ],
    },
    {
      id: "project-id",
      name: "projectId",
      label: "Project ID",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "project-details",
      order: 1,
      width: "half",
      helpText: "ID of the project associated with this drawing",
    },
    {
      id: "project-name",
      name: "projectName",
      label: "Project Name",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "project-details",
      order: 2,
      width: "half",
    },
    {
      id: "beneficiary-id",
      name: "beneficiaryId",
      label: "Beneficiary ID",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "project-details",
      order: 3,
      width: "half",
    },
    {
      id: "architect-name",
      name: "architectName",
      label: "Architect/Designer",
      type: FieldType.TEXT,
      required: true,
      section: "project-details",
      order: 4,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Architect/Designer name is required",
        },
      ],
    },
    {
      id: "drawing-file",
      name: "drawingFile",
      label: "Drawing File",
      type: FieldType.FILE,
      required: true,
      section: "drawing-details",
      order: 1,
      width: "full",
      helpText: "Upload the drawing file (PDF/CAD, max 25MB)",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Drawing file is required",
        },
      ],
    },
    {
      id: "drawing-description",
      name: "drawingDescription",
      label: "Drawing Description",
      type: FieldType.TEXTAREA,
      required: true,
      section: "drawing-details",
      order: 2,
      width: "full",
      placeholder: "Provide a detailed description of the drawing",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Drawing description is required",
        },
      ],
    },
    {
      id: "drawing-scale",
      name: "drawingScale",
      label: "Scale",
      type: FieldType.TEXT,
      required: true,
      section: "drawing-details",
      order: 3,
      width: "half",
      placeholder: "e.g., 1:50, 1:100",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Drawing scale is required",
        },
      ],
    },
    {
      id: "drawing-date",
      name: "drawingDate",
      label: "Drawing Date",
      type: FieldType.DATE,
      required: true,
      section: "drawing-details",
      order: 4,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Drawing date is required",
        },
      ],
    },
    {
      id: "reviewer-comments",
      name: "reviewerComments",
      label: "Reviewer Comments",
      type: FieldType.TEXTAREA,
      required: false,
      section: "review-comments",
      order: 1,
      width: "full",
      placeholder: "Enter any comments or feedback about the drawing",
    },
    {
      id: "technical-compliance",
      name: "technicalCompliance",
      label: "Technical Compliance",
      type: FieldType.SELECT,
      required: true,
      section: "review-comments",
      order: 2,
      width: "half",
      options: [
        { value: "compliant", label: "Fully Compliant" },
        { value: "minor-issues", label: "Minor Issues" },
        { value: "major-issues", label: "Major Issues" },
        { value: "non-compliant", label: "Non-Compliant" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Technical compliance assessment is required",
        },
      ],
    },
    {
      id: "safety-compliance",
      name: "safetyCompliance",
      label: "Safety Compliance",
      type: FieldType.SELECT,
      required: true,
      section: "review-comments",
      order: 3,
      width: "half",
      options: [
        { value: "compliant", label: "Fully Compliant" },
        { value: "minor-issues", label: "Minor Issues" },
        { value: "major-issues", label: "Major Issues" },
        { value: "non-compliant", label: "Non-Compliant" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Safety compliance assessment is required",
        },
      ],
    },
    {
      id: "approval-status",
      name: "approvalStatus",
      label: "Approval Status",
      type: FieldType.SELECT,
      required: true,
      section: "approval-details",
      order: 1,
      width: "half",
      options: [
        { value: "approved", label: "Approved" },
        { value: "approved-with-comments", label: "Approved with Comments" },
        { value: "revise-resubmit", label: "Revise and Resubmit" },
        { value: "rejected", label: "Rejected" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Approval status is required",
        },
      ],
    },
    {
      id: "approval-date",
      name: "approvalDate",
      label: "Approval Date",
      type: FieldType.DATE,
      required: true,
      section: "approval-details",
      order: 2,
      width: "half",
      defaultValue: new Date().toISOString().split("T")[0],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Approval date is required",
        },
      ],
    },
    {
      id: "approver-name",
      name: "approverName",
      label: "Approver Name",
      type: FieldType.TEXT,
      required: true,
      section: "approval-details",
      order: 3,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Approver name is required",
        },
      ],
    },
    {
      id: "approver-signature",
      name: "approverSignature",
      label: "Approver Signature",
      type: FieldType.SIGNATURE,
      required: true,
      section: "approval-details",
      order: 4,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Approver signature is required",
        },
      ],
    },
    {
      id: "approval-notes",
      name: "approvalNotes",
      label: "Approval Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "approval-details",
      order: 5,
      width: "full",
      placeholder: "Enter any additional notes regarding the approval decision",
    },
  ],
  dependencies: [],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

/**
 * Final Inspection Form (F12.3)
 * Used to document the final inspection of completed modifications or construction
 */
export const finalInspection: FormMetadata = {
  id: "final-inspection-form",
  title: "Final Inspection",
  description:
    "Document the final inspection of completed modifications or construction",
  module: FormModule.DRAWING,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: ["admin", "manager", "inspector", "case-manager"],
    [FormPermission.CREATE]: ["admin", "manager", "inspector"],
    [FormPermission.EDIT]: ["admin", "manager", "inspector"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["admin", "manager"],
    [FormPermission.REJECT]: ["admin", "manager"],
    [FormPermission.SUBMIT]: ["admin", "manager", "inspector"],
    [FormPermission.PRINT]: ["admin", "manager", "inspector", "case-manager"],
    [FormPermission.EXPORT]: ["admin", "manager"],
  },
  clientTypes: [
    ClientType.FDF,
    ClientType.ADHA,
    ClientType.CASH,
    ClientType.OTHER,
  ],
  sections: [
    {
      id: "inspection-information",
      title: "Inspection Information",
      description: "Basic information about the inspection",
      order: 1,
      collapsible: false,
    },
    {
      id: "project-details",
      title: "Project Details",
      description: "Information about the associated project",
      order: 2,
      collapsible: false,
    },
    {
      id: "inspection-checklist",
      title: "Inspection Checklist",
      description: "Items to be inspected",
      order: 3,
      collapsible: false,
    },
    {
      id: "safety-compliance",
      title: "Safety Compliance",
      description: "Safety-related inspection items",
      order: 4,
      collapsible: false,
    },
    {
      id: "inspection-results",
      title: "Inspection Results",
      description: "Results and findings of the inspection",
      order: 5,
      collapsible: false,
    },
    {
      id: "documentation",
      title: "Documentation",
      description: "Supporting documents for the inspection",
      order: 6,
      collapsible: true,
    },
  ],
  fields: [
    {
      id: "inspection-id",
      name: "inspectionId",
      label: "Inspection ID",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "inspection-information",
      order: 1,
      width: "half",
      helpText: "Unique identifier for the inspection",
    },
    {
      id: "inspection-date",
      name: "inspectionDate",
      label: "Inspection Date",
      type: FieldType.DATE,
      required: true,
      section: "inspection-information",
      order: 2,
      width: "half",
      defaultValue: new Date().toISOString().split("T")[0],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Inspection date is required",
        },
      ],
    },
    {
      id: "inspector-name",
      name: "inspectorName",
      label: "Inspector Name",
      type: FieldType.TEXT,
      required: true,
      section: "inspection-information",
      order: 3,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Inspector name is required",
        },
      ],
    },
    {
      id: "inspection-type",
      name: "inspectionType",
      label: "Inspection Type",
      type: FieldType.SELECT,
      required: true,
      section: "inspection-information",
      order: 4,
      width: "half",
      options: [
        { value: "final", label: "Final Inspection" },
        { value: "follow-up", label: "Follow-up Inspection" },
        { value: "warranty", label: "Warranty Inspection" },
        { value: "special", label: "Special Inspection" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Inspection type is required",
        },
      ],
    },
    {
      id: "project-id",
      name: "projectId",
      label: "Project ID",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "project-details",
      order: 1,
      width: "half",
      helpText: "ID of the project associated with this inspection",
    },
    {
      id: "project-name",
      name: "projectName",
      label: "Project Name",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "project-details",
      order: 2,
      width: "half",
    },
    {
      id: "beneficiary-id",
      name: "beneficiaryId",
      label: "Beneficiary ID",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "project-details",
      order: 3,
      width: "half",
    },
    {
      id: "contractor-name",
      name: "contractorName",
      label: "Contractor Name",
      type: FieldType.TEXT,
      required: true,
      section: "project-details",
      order: 4,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Contractor name is required",
        },
      ],
    },
    {
      id: "structural-integrity",
      name: "structuralIntegrity",
      label: "Structural Integrity",
      type: FieldType.SELECT,
      required: true,
      section: "inspection-checklist",
      order: 1,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        { value: "fail", label: "Fail" },
        { value: "na", label: "Not Applicable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Structural integrity assessment is required",
        },
      ],
    },
    {
      id: "electrical-systems",
      name: "electricalSystems",
      label: "Electrical Systems",
      type: FieldType.SELECT,
      required: true,
      section: "inspection-checklist",
      order: 2,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        { value: "fail", label: "Fail" },
        { value: "na", label: "Not Applicable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Electrical systems assessment is required",
        },
      ],
    },
    {
      id: "plumbing-systems",
      name: "plumbingSystems",
      label: "Plumbing Systems",
      type: FieldType.SELECT,
      required: true,
      section: "inspection-checklist",
      order: 3,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        { value: "fail", label: "Fail" },
        { value: "na", label: "Not Applicable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Plumbing systems assessment is required",
        },
      ],
    },
    {
      id: "finishes-quality",
      name: "finishesQuality",
      label: "Finishes Quality",
      type: FieldType.SELECT,
      required: true,
      section: "inspection-checklist",
      order: 4,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        { value: "fail", label: "Fail" },
        { value: "na", label: "Not Applicable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Finishes quality assessment is required",
        },
      ],
    },
    {
      id: "accessibility-features",
      name: "accessibilityFeatures",
      label: "Accessibility Features",
      type: FieldType.SELECT,
      required: true,
      section: "inspection-checklist",
      order: 5,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        { value: "fail", label: "Fail" },
        { value: "na", label: "Not Applicable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Accessibility features assessment is required",
        },
      ],
    },
    {
      id: "hvac-systems",
      name: "hvacSystems",
      label: "HVAC Systems",
      type: FieldType.SELECT,
      required: true,
      section: "inspection-checklist",
      order: 6,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        { value: "fail", label: "Fail" },
        { value: "na", label: "Not Applicable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "HVAC systems assessment is required",
        },
      ],
    },
    {
      id: "fire-safety",
      name: "fireSafety",
      label: "Fire Safety",
      type: FieldType.SELECT,
      required: true,
      section: "safety-compliance",
      order: 1,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        { value: "fail", label: "Fail" },
        { value: "na", label: "Not Applicable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Fire safety assessment is required",
        },
      ],
    },
    {
      id: "emergency-exits",
      name: "emergencyExits",
      label: "Emergency Exits",
      type: FieldType.SELECT,
      required: true,
      section: "safety-compliance",
      order: 2,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        { value: "fail", label: "Fail" },
        { value: "na", label: "Not Applicable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Emergency exits assessment is required",
        },
      ],
    },
    {
      id: "trip-hazards",
      name: "tripHazards",
      label: "Trip Hazards",
      type: FieldType.SELECT,
      required: true,
      section: "safety-compliance",
      order: 3,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        { value: "fail", label: "Fail" },
        { value: "na", label: "Not Applicable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Trip hazards assessment is required",
        },
      ],
    },
    {
      id: "electrical-safety",
      name: "electricalSafety",
      label: "Electrical Safety",
      type: FieldType.SELECT,
      required: true,
      section: "safety-compliance",
      order: 4,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        { value: "fail", label: "Fail" },
        { value: "na", label: "Not Applicable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Electrical safety assessment is required",
        },
      ],
    },
    {
      id: "overall-result",
      name: "overallResult",
      label: "Overall Inspection Result",
      type: FieldType.SELECT,
      required: true,
      section: "inspection-results",
      order: 1,
      width: "half",
      options: [
        { value: "pass", label: "Pass - No Issues" },
        { value: "pass-minor", label: "Pass - Minor Issues" },
        { value: "conditional", label: "Conditional Pass" },
        { value: "fail", label: "Fail - Requires Remediation" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Overall inspection result is required",
        },
      ],
    },
    {
      id: "deficiencies-found",
      name: "deficienciesFound",
      label: "Deficiencies Found",
      type: FieldType.TEXTAREA,
      required: false,
      section: "inspection-results",
      order: 2,
      width: "full",
      placeholder: "List any deficiencies found during inspection",
      conditional: {
        field: "overallResult",
        operator: "in",
        value: ["pass-minor", "conditional", "fail"],
      },
    },
    {
      id: "remediation-required",
      name: "remediationRequired",
      label: "Remediation Required",
      type: FieldType.TEXTAREA,
      required: false,
      section: "inspection-results",
      order: 3,
      width: "full",
      placeholder: "Describe remediation actions required",
      conditional: {
        field: "overallResult",
        operator: "in",
        value: ["conditional", "fail"],
      },
    },
    {
      id: "follow-up-required",
      name: "followUpRequired",
      label: "Follow-up Inspection Required",
      type: FieldType.RADIO,
      required: true,
      section: "inspection-results",
      order: 4,
      width: "half",
      options: [
        { value: "yes", label: "Yes" },
        { value: "no", label: "No" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Follow-up requirement must be specified",
        },
      ],
    },
    {
      id: "follow-up-date",
      name: "followUpDate",
      label: "Follow-up Date",
      type: FieldType.DATE,
      required: false,
      section: "inspection-results",
      order: 5,
      width: "half",
      conditional: {
        field: "followUpRequired",
        operator: "equals",
        value: "yes",
      },
      validation: [
        {
          type: ValidationRuleType.CUSTOM,
          value: (value: string) => {
            if (!value) return true;
            const followUpDate = new Date(value);
            const today = new Date();
            return followUpDate > today;
          },
          message: "Follow-up date must be in the future",
        },
      ],
    },
    {
      id: "inspector-notes",
      name: "inspectorNotes",
      label: "Inspector Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "inspection-results",
      order: 6,
      width: "full",
      placeholder: "Enter any additional notes or observations",
    },
    {
      id: "inspection-photos",
      name: "inspectionPhotos",
      label: "Inspection Photos",
      type: FieldType.FILE,
      required: false,
      section: "documentation",
      order: 1,
      width: "full",
      helpText: "Upload photos from the inspection (JPEG/PNG, max 10MB each)",
      multiple: true,
    },
    {
      id: "inspector-signature",
      name: "inspectorSignature",
      label: "Inspector Signature",
      type: FieldType.SIGNATURE,
      required: true,
      section: "documentation",
      order: 2,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Inspector signature is required",
        },
      ],
    },
    {
      id: "contractor-signature",
      name: "contractorSignature",
      label: "Contractor Signature",
      type: FieldType.SIGNATURE,
      required: false,
      section: "documentation",
      order: 3,
      width: "half",
    },
    {
      id: "inspection-status",
      name: "inspectionStatus",
      label: "Inspection Status",
      type: FieldType.HIDDEN,
      required: false,
      section: "documentation",
      order: 4,
      width: "full",
      defaultValue: "Completed",
    },
  ],
  dependencies: [],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

// Register forms with the form registry
export function registerdrawingApproval() {
  formRegistry.registerForm(
    {
      id: drawingApproval.id,
      title: drawingApproval.title,
      description: drawingApproval.description,
      module: FormModule.DRAWING,
      clientTypes: drawingApproval.clientTypes,
      permissions: drawingApproval.permissions,
      dependencies: drawingApproval.dependencies,
      version: drawingApproval.version,
      path: "/drawing/approval",
      icon: "file-check",
      isActive: true,
    },
    drawingApproval,
  );
}


export function registerfinalInspection() {
  formRegistry.registerForm(
    {
      id: finalInspection.id,
      title: finalInspection.title,
      description: finalInspection.description,
      module: FormModule.DRAWING,
      clientTypes: finalInspection.clientTypes,
      permissions: finalInspection.permissions,
      dependencies: finalInspection.dependencies,
      version: finalInspection.version,
      path: "/drawing/inspection",
      icon: "clipboard-check",
      isActive: true,
    },
    finalInspection,
  );

}
