import {
  ClientType,
  FieldType,
  FormMetadata,
  FormModule,
  FormPermission,
  ValidationRuleType,
} from "../types";
import { formRegistry } from "../registry";

/**
 * Price Adjustment Form (F14.2)
 * Used to document and approve price adjustments for materials and services
 */
export const priceAdjustment: FormMetadata = {
  id: "price-adjustment-form",
  title: "Price Adjustment",
  description:
    "Document and approve price adjustments for materials and services",
  module: FormModule.PRICE_LIST,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: [
      "admin",
      "manager",
      "procurement-officer",
      "finance-officer",
    ],
    [FormPermission.CREATE]: ["admin", "manager", "procurement-officer"],
    [FormPermission.EDIT]: ["admin", "manager", "procurement-officer"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["admin", "manager", "finance-officer"],
    [FormPermission.REJECT]: ["admin", "manager", "finance-officer"],
    [FormPermission.SUBMIT]: ["admin", "manager", "procurement-officer"],
    [FormPermission.PRINT]: [
      "admin",
      "manager",
      "procurement-officer",
      "finance-officer",
    ],
    [FormPermission.EXPORT]: ["admin", "manager", "finance-officer"],
  },
  clientTypes: [
    ClientType.FDF,
    ClientType.ADHA,
    ClientType.CASH,
    ClientType.OTHER,
  ],
  sections: [
    {
      id: "adjustment-information",
      title: "Adjustment Information",
      description: "Basic information about the price adjustment",
      order: 1,
      collapsible: false,
    },
    {
      id: "item-details",
      title: "Item Details",
      description: "Information about the items being adjusted",
      order: 2,
      collapsible: false,
    },
    {
      id: "price-information",
      title: "Price Information",
      description: "Current and new price details",
      order: 3,
      collapsible: false,
    },
    {
      id: "justification",
      title: "Justification",
      description: "Reasons and supporting information for the adjustment",
      order: 4,
      collapsible: false,
    },
    {
      id: "market-analysis",
      title: "Market Analysis",
      description: "Analysis of market conditions affecting prices",
      order: 5,
      collapsible: true,
    },
    {
      id: "approval-information",
      title: "Approval Information",
      description: "Approval details for the price adjustment",
      order: 6,
      collapsible: false,
    },
  ],
  fields: [
    {
      id: "adjustment-id",
      name: "adjustmentId",
      label: "Adjustment ID",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "adjustment-information",
      order: 1,
      width: "half",
      helpText: "Unique identifier for the price adjustment",
    },
    {
      id: "adjustment-date",
      name: "adjustmentDate",
      label: "Adjustment Date",
      type: FieldType.DATE,
      required: true,
      section: "adjustment-information",
      order: 2,
      width: "half",
      defaultValue: new Date().toISOString().split("T")[0],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Adjustment date is required",
        },
      ],
    },
    {
      id: "adjustment-type",
      name: "adjustmentType",
      label: "Adjustment Type",
      type: FieldType.SELECT,
      required: true,
      section: "adjustment-information",
      order: 3,
      width: "half",
      options: [
        { value: "increase", label: "Price Increase" },
        { value: "decrease", label: "Price Decrease" },
        { value: "new-item", label: "New Item Addition" },
        { value: "bulk-update", label: "Bulk Price Update" },
        { value: "seasonal", label: "Seasonal Adjustment" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Adjustment type is required",
        },
      ],
    },
    {
      id: "effective-date",
      name: "effectiveDate",
      label: "Effective Date",
      type: FieldType.DATE,
      required: true,
      section: "adjustment-information",
      order: 4,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Effective date is required",
        },
        {
          type: ValidationRuleType.CUSTOM,
          value: (value: string, formData: any) => {
            if (!value || !formData.adjustmentDate) return true;
            const effectiveDate = new Date(value);
            const adjustmentDate = new Date(formData.adjustmentDate);
            return effectiveDate >= adjustmentDate;
          },
          message: "Effective date must be on or after the adjustment date",
        },
      ],
    },
    {
      id: "item-category",
      name: "itemCategory",
      label: "Item Category",
      type: FieldType.SELECT,
      required: true,
      section: "item-details",
      order: 1,
      width: "half",
      options: [
        { value: "materials", label: "Construction Materials" },
        { value: "fixtures", label: "Fixtures & Fittings" },
        { value: "appliances", label: "Appliances" },
        { value: "tools", label: "Tools & Equipment" },
        { value: "services", label: "Services" },
        { value: "labor", label: "Labor" },
        { value: "other", label: "Other" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Item category is required",
        },
      ],
    },
    {
      id: "item-id",
      name: "itemId",
      label: "Item ID",
      type: FieldType.TEXT,
      required: true,
      section: "item-details",
      order: 2,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Item ID is required",
        },
      ],
    },
    {
      id: "item-name",
      name: "itemName",
      label: "Item Name",
      type: FieldType.TEXT,
      required: true,
      section: "item-details",
      order: 3,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Item name is required",
        },
      ],
    },
    {
      id: "item-description",
      name: "itemDescription",
      label: "Item Description",
      type: FieldType.TEXTAREA,
      required: true,
      section: "item-details",
      order: 4,
      width: "full",
      placeholder: "Provide a detailed description of the item",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Item description is required",
        },
      ],
    },
    {
      id: "supplier-id",
      name: "supplierId",
      label: "Supplier ID",
      type: FieldType.TEXT,
      required: true,
      section: "item-details",
      order: 5,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Supplier ID is required",
        },
      ],
    },
    {
      id: "supplier-name",
      name: "supplierName",
      label: "Supplier Name",
      type: FieldType.TEXT,
      required: true,
      section: "item-details",
      order: 6,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Supplier name is required",
        },
      ],
    },
    {
      id: "current-price",
      name: "currentPrice",
      label: "Current Price",
      type: FieldType.NUMBER,
      required: true,
      section: "price-information",
      order: 1,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Current price is required",
        },
        {
          type: ValidationRuleType.MIN,
          value: 0,
          message: "Current price must be greater than or equal to 0",
        },
      ],
    },
    {
      id: "new-price",
      name: "newPrice",
      label: "New Price",
      type: FieldType.NUMBER,
      required: true,
      section: "price-information",
      order: 2,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "New price is required",
        },
        {
          type: ValidationRuleType.MIN,
          value: 0,
          message: "New price must be greater than or equal to 0",
        },
      ],
    },
    {
      id: "price-difference",
      name: "priceDifference",
      label: "Price Difference",
      type: FieldType.CALCULATED,
      readOnly: true,
      required: false,
      section: "price-information",
      order: 3,
      width: "half",
      calculationFormula: "newPrice - currentPrice",
      helpText: "Calculated difference between new and current price",
    },
    {
      id: "percentage-change",
      name: "percentageChange",
      label: "Percentage Change",
      type: FieldType.CALCULATED,
      readOnly: true,
      required: false,
      section: "price-information",
      order: 4,
      width: "half",
      calculationFormula: "((newPrice - currentPrice) / currentPrice) * 100",
      helpText: "Calculated percentage change in price",
    },
    {
      id: "currency",
      name: "currency",
      label: "Currency",
      type: FieldType.SELECT,
      required: true,
      section: "price-information",
      order: 5,
      width: "half",
      options: [
        { value: "SAR", label: "Saudi Riyal (SAR)" },
        { value: "USD", label: "US Dollar (USD)" },
        { value: "EUR", label: "Euro (EUR)" },
        { value: "GBP", label: "British Pound (GBP)" },
        { value: "AED", label: "UAE Dirham (AED)" },
      ],
      defaultValue: "SAR",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Currency is required",
        },
      ],
    },
    {
      id: "unit-of-measure",
      name: "unitOfMeasure",
      label: "Unit of Measure",
      type: FieldType.SELECT,
      required: true,
      section: "price-information",
      order: 6,
      width: "half",
      options: [
        { value: "each", label: "Each" },
        { value: "kg", label: "Kilogram" },
        { value: "m", label: "Meter" },
        { value: "m2", label: "Square Meter" },
        { value: "m3", label: "Cubic Meter" },
        { value: "hour", label: "Hour" },
        { value: "day", label: "Day" },
        { value: "liter", label: "Liter" },
        { value: "set", label: "Set" },
        { value: "roll", label: "Roll" },
        { value: "box", label: "Box" },
        { value: "other", label: "Other" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Unit of measure is required",
        },
      ],
    },
    {
      id: "adjustment-reason",
      name: "adjustmentReason",
      label: "Adjustment Reason",
      type: FieldType.SELECT,
      required: true,
      section: "justification",
      order: 1,
      width: "half",
      options: [
        { value: "supplier-increase", label: "Supplier Price Increase" },
        { value: "market-fluctuation", label: "Market Price Fluctuation" },
        { value: "currency-exchange", label: "Currency Exchange Rate Change" },
        { value: "seasonal-factors", label: "Seasonal Factors" },
        { value: "bulk-discount", label: "Bulk Purchase Discount" },
        { value: "quality-change", label: "Quality/Specification Change" },
        { value: "negotiated-reduction", label: "Negotiated Price Reduction" },
        { value: "other", label: "Other" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Adjustment reason is required",
        },
      ],
    },
    {
      id: "other-reason-details",
      name: "otherReasonDetails",
      label: "Other Reason Details",
      type: FieldType.TEXTAREA,
      required: false,
      section: "justification",
      order: 2,
      width: "half",
      placeholder: "Provide details for the other reason",
      conditional: {
        field: "adjustmentReason",
        operator: "equals",
        value: "other",
      },
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Other reason details are required when 'Other' is selected",
        },
      ],
    },
    {
      id: "justification-details",
      name: "justificationDetails",
      label: "Justification Details",
      type: FieldType.TEXTAREA,
      required: true,
      section: "justification",
      order: 3,
      width: "full",
      placeholder: "Provide detailed justification for the price adjustment",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Justification details are required",
        },
      ],
    },
    {
      id: "supporting-documents",
      name: "supportingDocuments",
      label: "Supporting Documents",
      type: FieldType.FILE,
      required: false,
      section: "justification",
      order: 4,
      width: "full",
      helpText:
        "Upload any supporting documents (supplier quotes, market reports, etc.)",
      multiple: true,
    },
    {
      id: "impact-assessment",
      name: "impactAssessment",
      label: "Impact Assessment",
      type: FieldType.TEXTAREA,
      required: true,
      section: "justification",
      order: 5,
      width: "full",
      placeholder:
        "Describe the impact of this price adjustment on projects and budgets",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Impact assessment is required",
        },
      ],
    },
    {
      id: "market-research-conducted",
      name: "marketResearchConducted",
      label: "Market Research Conducted",
      type: FieldType.RADIO,
      required: true,
      section: "market-analysis",
      order: 1,
      width: "half",
      options: [
        { value: "yes", label: "Yes" },
        { value: "no", label: "No" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Please indicate if market research was conducted",
        },
      ],
    },
    {
      id: "market-research-details",
      name: "marketResearchDetails",
      label: "Market Research Details",
      type: FieldType.TEXTAREA,
      required: false,
      section: "market-analysis",
      order: 2,
      width: "full",
      placeholder: "Provide details of the market research conducted",
      conditional: {
        field: "marketResearchConducted",
        operator: "equals",
        value: "yes",
      },
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message:
            "Market research details are required when research was conducted",
        },
      ],
    },
    {
      id: "competitor-prices",
      name: "competitorPrices",
      label: "Competitor Prices",
      type: FieldType.TEXTAREA,
      required: false,
      section: "market-analysis",
      order: 3,
      width: "full",
      placeholder: "List prices from other suppliers for comparison",
      conditional: {
        field: "marketResearchConducted",
        operator: "equals",
        value: "yes",
      },
    },
    {
      id: "market-trends",
      name: "marketTrends",
      label: "Market Trends",
      type: FieldType.TEXTAREA,
      required: false,
      section: "market-analysis",
      order: 4,
      width: "full",
      placeholder:
        "Describe relevant market trends affecting this price adjustment",
    },
    {
      id: "requested-by",
      name: "requestedBy",
      label: "Requested By",
      type: FieldType.TEXT,
      required: true,
      section: "approval-information",
      order: 1,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Requester name is required",
        },
      ],
    },
    {
      id: "requester-position",
      name: "requesterPosition",
      label: "Requester Position",
      type: FieldType.TEXT,
      required: true,
      section: "approval-information",
      order: 2,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Requester position is required",
        },
      ],
    },
    {
      id: "approved-by",
      name: "approvedBy",
      label: "Approved By",
      type: FieldType.TEXT,
      required: false,
      section: "approval-information",
      order: 3,
      width: "half",
    },
    {
      id: "approver-position",
      name: "approverPosition",
      label: "Approver Position",
      type: FieldType.TEXT,
      required: false,
      section: "approval-information",
      order: 4,
      width: "half",
    },
    {
      id: "approval-date",
      name: "approvalDate",
      label: "Approval Date",
      type: FieldType.DATE,
      required: false,
      section: "approval-information",
      order: 5,
      width: "half",
    },
    {
      id: "approver-signature",
      name: "approverSignature",
      label: "Approver Signature",
      type: FieldType.SIGNATURE,
      required: false,
      section: "approval-information",
      order: 6,
      width: "half",
    },
    {
      id: "approval-status",
      name: "approvalStatus",
      label: "Approval Status",
      type: FieldType.SELECT,
      required: true,
      section: "approval-information",
      order: 7,
      width: "half",
      options: [
        { value: "draft", label: "Draft" },
        { value: "pending", label: "Pending Approval" },
        { value: "approved", label: "Approved" },
        { value: "rejected", label: "Rejected" },
        { value: "implemented", label: "Implemented" },
      ],
      defaultValue: "draft",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Approval status is required",
        },
      ],
    },
    {
      id: "approval-comments",
      name: "approvalComments",
      label: "Approval Comments",
      type: FieldType.TEXTAREA,
      required: false,
      section: "approval-information",
      order: 8,
      width: "full",
      placeholder: "Any comments regarding the approval decision",
    },
  ],
  dependencies: [],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

// Register forms with the form registry
export function registerpriceAdjustment() {

  formRegistry.registerForm(
    {
      id: priceAdjustment.id,
      title: priceAdjustment.title,
      description: priceAdjustment.description,
      module: FormModule.PRICE_LIST,
      clientTypes: priceAdjustment.clientTypes,
      permissions: priceAdjustment.permissions,
      dependencies: priceAdjustment.dependencies,
      version: priceAdjustment.version,
      path: "/price-list/adjustment",
      icon: "dollar-sign",
      isActive: true,
    },
    priceAdjustment,
  );
}