import {
  ClientType,
  FieldType,
  FormMetadata,
  FormModule,
  FormPermission,
  ValidationRuleType,
} from "../types";
import { formRegistry } from "../registry";

/**
 * Room Inspection Form (F04.5)
 * Used for conducting detailed inspections of rooms after modifications
 */
export const roomInspectionForm: FormMetadata = {
  id: "room-inspection-form",
  title: "Room Inspection",
  description: "Conduct detailed inspection of rooms after modifications",
  module: FormModule.ASSESSMENT,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: [
      "inspector",
      "supervisor",
      "admin",
      "project-manager",
    ],
    [FormPermission.CREATE]: ["inspector", "admin"],
    [FormPermission.EDIT]: ["inspector", "admin"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["supervisor", "admin"],
    [FormPermission.REJECT]: ["supervisor", "admin"],
    [FormPermission.SUBMIT]: ["inspector", "admin"],
    [FormPermission.PRINT]: [
      "inspector",
      "supervisor",
      "admin",
      "project-manager",
    ],
    [FormPermission.EXPORT]: ["supervisor", "admin"],
  },
  clientTypes: [ClientType.FDF, ClientType.ADHA, ClientType.CASH],
  sections: [
    {
      id: "inspection-info",
      title: "Inspection Information",
      description: "Basic information about the inspection",
      order: 1,
      collapsible: false,
    },
    {
      id: "room-details",
      title: "Room Details",
      description: "Details of the room being inspected",
      order: 2,
      collapsible: false,
    },
    {
      id: "structural-inspection",
      title: "Structural Inspection",
      description: "Inspection of structural elements",
      order: 3,
      collapsible: true,
    },
    {
      id: "accessibility-features",
      title: "Accessibility Features",
      description: "Inspection of accessibility features",
      order: 4,
      collapsible: true,
    },
    {
      id: "fixtures-inspection",
      title: "Fixtures & Fittings",
      description: "Inspection of fixtures and fittings",
      order: 5,
      collapsible: true,
    },
    {
      id: "documentation",
      title: "Documentation",
      description: "Photos and documentation of the inspection",
      order: 6,
      collapsible: true,
    },
  ],
  fields: [
    {
      id: "project-id",
      name: "projectId",
      label: "Project Reference",
      type: FieldType.SELECT,
      required: true,
      section: "inspection-info",
      order: 1,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/projects/list",
        valueField: "id",
        labelField: "projectName",
        filters: { status: "in-progress" },
      },
    },
    {
      id: "inspection-date",
      name: "inspectionDate",
      label: "Inspection Date",
      type: FieldType.DATE,
      required: true,
      section: "inspection-info",
      order: 2,
      width: "half",
      defaultValue: new Date().toISOString().split("T")[0],
    },
    {
      id: "inspector-name",
      name: "inspectorName",
      label: "Inspector Name",
      type: FieldType.SELECT,
      required: true,
      section: "inspection-info",
      order: 3,
      width: "half",
      dataSource: {
        type: "api",
        source: "/api/users/inspectors",
        valueField: "id",
        labelField: "fullName",
        filters: { active: true },
      },
    },
    {
      id: "room-id",
      name: "roomId",
      label: "Room Reference",
      type: FieldType.SELECT,
      required: true,
      section: "room-details",
      order: 1,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/projects/{projectId}/rooms",
        valueField: "id",
        labelField: "roomName",
        dependsOn: ["projectId"],
      },
      dependencies: [
        {
          type: "visibility",
          sourceField: "projectId",
          condition: "!!value",
          action: "visible = true",
        },
      ],
    },
    {
      id: "room-type",
      name: "roomType",
      label: "Room Type",
      type: FieldType.TEXT,
      required: true,
      section: "room-details",
      order: 2,
      width: "half",
      readOnly: true,
      dataSource: {
        type: "api",
        source: "/api/rooms/{roomId}/details",
        valueField: "roomType",
        labelField: "roomType",
        dependsOn: ["roomId"],
      },
    },
    {
      id: "modification-type",
      name: "modificationType",
      label: "Modification Type",
      type: FieldType.TEXT,
      required: true,
      section: "room-details",
      order: 3,
      width: "half",
      readOnly: true,
      dataSource: {
        type: "api",
        source: "/api/rooms/{roomId}/modifications",
        valueField: "modificationType",
        labelField: "modificationType",
        dependsOn: ["roomId"],
      },
    },
    {
      id: "structural-items",
      name: "structuralItems",
      label: "Structural Elements",
      type: FieldType.REPEATER,
      required: true,
      section: "structural-inspection",
      order: 1,
      width: "full",
      fields: [
        {
          id: "item-name",
          name: "itemName",
          label: "Element Name",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "floor", label: "Floor" },
            { value: "walls", label: "Walls" },
            { value: "ceiling", label: "Ceiling" },
            { value: "doorways", label: "Doorways" },
            { value: "windows", label: "Windows" },
            { value: "ramps", label: "Ramps" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "condition",
          name: "condition",
          label: "Condition",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "excellent", label: "Excellent" },
            { value: "good", label: "Good" },
            { value: "fair", label: "Fair" },
            { value: "poor", label: "Poor" },
            { value: "critical", label: "Critical" },
          ],
        },
        {
          id: "comments",
          name: "comments",
          label: "Comments",
          type: FieldType.TEXT,
          required: false,
          width: "third",
        },
      ],
    },
    {
      id: "structural-compliance",
      name: "structuralCompliance",
      label: "Structural Compliance",
      type: FieldType.SELECT,
      required: true,
      section: "structural-inspection",
      order: 2,
      width: "half",
      options: [
        { value: "compliant", label: "Fully Compliant" },
        { value: "minor-issues", label: "Minor Issues" },
        { value: "major-issues", label: "Major Issues" },
        { value: "non-compliant", label: "Non-Compliant" },
      ],
    },
    {
      id: "structural-notes",
      name: "structuralNotes",
      label: "Structural Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "structural-inspection",
      order: 3,
      width: "full",
      placeholder: "Enter any additional notes about structural elements",
    },
    {
      id: "accessibility-items",
      name: "accessibilityItems",
      label: "Accessibility Features",
      type: FieldType.REPEATER,
      required: true,
      section: "accessibility-features",
      order: 1,
      width: "full",
      fields: [
        {
          id: "feature-name",
          name: "featureName",
          label: "Feature Name",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "grab-bars", label: "Grab Bars" },
            { value: "handrails", label: "Handrails" },
            { value: "ramps", label: "Ramps" },
            { value: "door-width", label: "Door Width" },
            { value: "threshold", label: "Threshold Height" },
            { value: "turning-space", label: "Turning Space" },
            { value: "shower-access", label: "Shower Access" },
            { value: "toilet-height", label: "Toilet Height" },
            { value: "sink-access", label: "Sink Access" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "compliance",
          name: "compliance",
          label: "Compliance",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "compliant", label: "Compliant" },
            { value: "non-compliant", label: "Non-Compliant" },
            { value: "not-applicable", label: "Not Applicable" },
          ],
        },
        {
          id: "measurements",
          name: "measurements",
          label: "Measurements (cm)",
          type: FieldType.TEXT,
          required: false,
          width: "third",
          placeholder: "e.g., 85cm height",
        },
      ],
    },
    {
      id: "accessibility-compliance",
      name: "accessibilityCompliance",
      label: "Overall Accessibility Compliance",
      type: FieldType.SELECT,
      required: true,
      section: "accessibility-features",
      order: 2,
      width: "half",
      options: [
        { value: "compliant", label: "Fully Compliant" },
        { value: "minor-issues", label: "Minor Issues" },
        { value: "major-issues", label: "Major Issues" },
        { value: "non-compliant", label: "Non-Compliant" },
      ],
    },
    {
      id: "accessibility-notes",
      name: "accessibilityNotes",
      label: "Accessibility Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "accessibility-features",
      order: 3,
      width: "full",
      placeholder: "Enter any additional notes about accessibility features",
    },
    {
      id: "fixtures-items",
      name: "fixturesItems",
      label: "Fixtures & Fittings",
      type: FieldType.REPEATER,
      required: true,
      section: "fixtures-inspection",
      order: 1,
      width: "full",
      fields: [
        {
          id: "fixture-name",
          name: "fixtureName",
          label: "Fixture Name",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "sink", label: "Sink" },
            { value: "toilet", label: "Toilet" },
            { value: "shower", label: "Shower" },
            { value: "bathtub", label: "Bathtub" },
            { value: "grab-bars", label: "Grab Bars" },
            { value: "handrails", label: "Handrails" },
            { value: "cabinets", label: "Cabinets" },
            { value: "countertops", label: "Countertops" },
            { value: "lighting", label: "Lighting" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "condition",
          name: "condition",
          label: "Condition",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "excellent", label: "Excellent" },
            { value: "good", label: "Good" },
            { value: "fair", label: "Fair" },
            { value: "poor", label: "Poor" },
            { value: "critical", label: "Critical" },
          ],
        },
        {
          id: "comments",
          name: "comments",
          label: "Comments",
          type: FieldType.TEXT,
          required: false,
          width: "third",
        },
      ],
    },
    {
      id: "fixtures-compliance",
      name: "fixturesCompliance",
      label: "Fixtures Compliance",
      type: FieldType.SELECT,
      required: true,
      section: "fixtures-inspection",
      order: 2,
      width: "half",
      options: [
        { value: "compliant", label: "Fully Compliant" },
        { value: "minor-issues", label: "Minor Issues" },
        { value: "major-issues", label: "Major Issues" },
        { value: "non-compliant", label: "Non-Compliant" },
      ],
    },
    {
      id: "fixtures-notes",
      name: "fixturesNotes",
      label: "Fixtures Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "fixtures-inspection",
      order: 3,
      width: "full",
      placeholder: "Enter any additional notes about fixtures and fittings",
    },
    {
      id: "inspection-photos",
      name: "inspectionPhotos",
      label: "Inspection Photos",
      type: FieldType.IMAGE,
      required: true,
      section: "documentation",
      order: 1,
      width: "full",
      helpText: "Upload photos of the inspected room (at least 3 photos)",
      multiple: true,
      validation: [
        {
          type: ValidationRuleType.CUSTOM,
          value: (value: any[]) => value && value.length >= 3,
          message: "At least 3 photos are required",
        },
      ],
    },
    {
      id: "overall-assessment",
      name: "overallAssessment",
      label: "Overall Assessment",
      type: FieldType.SELECT,
      required: true,
      section: "documentation",
      order: 2,
      width: "half",
      options: [
        { value: "pass", label: "Pass" },
        {
          value: "pass-with-recommendations",
          label: "Pass with Recommendations",
        },
        { value: "requires-minor-fixes", label: "Requires Minor Fixes" },
        { value: "requires-major-fixes", label: "Requires Major Fixes" },
        { value: "fail", label: "Fail" },
      ],
    },
    {
      id: "reinspection-required",
      name: "reinspectionRequired",
      label: "Reinspection Required",
      type: FieldType.CHECKBOX,
      required: true,
      section: "documentation",
      order: 3,
      width: "half",
      defaultValue: false,
    },
    {
      id: "reinspection-date",
      name: "reinspectionDate",
      label: "Reinspection Date",
      type: FieldType.DATE,
      required: false,
      section: "documentation",
      order: 4,
      width: "half",
      dependencies: [
        {
          type: "visibility",
          sourceField: "reinspectionRequired",
          condition: "value === true",
          action: "visible = true",
        },
        {
          type: "requirement",
          sourceField: "reinspectionRequired",
          condition: "value === true",
          action: "required = true",
        },
      ],
    },
    {
      id: "inspector-comments",
      name: "inspectorComments",
      label: "Inspector Comments",
      type: FieldType.TEXTAREA,
      required: true,
      section: "documentation",
      order: 5,
      width: "full",
      placeholder: "Enter detailed comments about the inspection",
    },
    {
      id: "inspector-signature",
      name: "inspectorSignature",
      label: "Inspector Signature",
      type: FieldType.SIGNATURE,
      required: true,
      section: "documentation",
      order: 6,
      width: "full",
    },
  ],
  dependencies: [
    {
      formId: "project-creation-form",
      description: "Room inspection requires an active project",
      type: "prerequisite",
      required: true,
    },
  ],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

// Register form with the form registry
formRegistry.registerForm(
  {
    id: roomInspectionForm.id,
    title: roomInspectionForm.title,
    description: roomInspectionForm.description,
    module: roomInspectionForm.module,
    clientTypes: roomInspectionForm.clientTypes,
    permissions: roomInspectionForm.permissions,
    dependencies: roomInspectionForm.dependencies,
    version: roomInspectionForm.version,
    path: "/assessments/room-inspection",
    icon: "check-square",
    isActive: true,
  },
  roomInspectionForm,
);
