import {
  ClientType,
  FieldType,
  FormMetadata,
  FormModule,
  FormPermission,
  ValidationRuleType,
} from "../types";
import { formRegistry } from "../registry";

/**
 * Room Measurement Form
 * Used for recording detailed room measurements
 */
export const roomMeasurementForm: FormMetadata = {
  id: "room-measurement-form",
  title: "Room Measurement",
  description: "Record detailed measurements for a room",
  module: FormModule.ASSESSMENT,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: ["assessor", "supervisor", "admin"],
    [FormPermission.CREATE]: ["assessor", "admin"],
    [FormPermission.EDIT]: ["assessor", "admin"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["supervisor", "admin"],
    [FormPermission.REJECT]: ["supervisor", "admin"],
    [FormPermission.SUBMIT]: ["assessor", "admin"],
    [FormPermission.PRINT]: ["assessor", "supervisor", "admin"],
    [FormPermission.EXPORT]: ["supervisor", "admin"],
  },
  clientTypes: [ClientType.FDF, ClientType.ADHA, ClientType.CASH],
  sections: [
    {
      id: "room-info",
      title: "Room Information",
      description: "Basic information about the room",
      order: 1,
      collapsible: false,
    },
    {
      id: "dimensions",
      title: "Room Dimensions",
      description: "Detailed measurements of the room",
      order: 2,
      collapsible: false,
    },
    {
      id: "doorways",
      title: "Doorways",
      description: "Measurements of doorways in the room",
      order: 3,
      collapsible: true,
    },
    {
      id: "windows",
      title: "Windows",
      description: "Measurements of windows in the room",
      order: 4,
      collapsible: true,
    },
    {
      id: "fixtures",
      title: "Fixtures & Features",
      description: "Details of fixtures and features in the room",
      order: 5,
      collapsible: true,
    },
  ],
  fields: [
    {
      id: "assessment-id",
      name: "assessmentId",
      label: "Assessment Reference",
      type: FieldType.REFERENCE,
      required: true,
      section: "room-info",
      order: 1,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/assessments/initial/list",
        valueField: "id",
        labelField: "title",
        filters: { status: "active" },
      },
    },
    {
      id: "room-type",
      name: "roomType",
      label: "Room Type",
      type: FieldType.SELECT,
      required: true,
      section: "room-info",
      order: 2,
      width: "half",
      options: [
        { value: "bathroom", label: "Bathroom" },
        { value: "kitchen", label: "Kitchen" },
        { value: "bedroom", label: "Bedroom" },
        { value: "livingRoom", label: "Living Room" },
        { value: "entrance", label: "Entrance/Hallway" },
        { value: "stairs", label: "Stairs" },
      ],
    },
    {
      id: "room-name",
      name: "roomName",
      label: "Room Name/Identifier",
      type: FieldType.TEXT,
      placeholder: "e.g., Master Bathroom, Kitchen 1",
      required: true,
      section: "room-info",
      order: 3,
      width: "half",
    },
    {
      id: "floor-level",
      name: "floorLevel",
      label: "Floor Level",
      type: FieldType.NUMBER,
      required: true,
      section: "room-info",
      order: 4,
      width: "half",
      defaultValue: 1,
    },
    {
      id: "room-length",
      name: "roomLength",
      label: "Room Length (cm)",
      type: FieldType.NUMBER,
      required: true,
      section: "dimensions",
      order: 1,
      width: "third",
      validation: [
        {
          type: ValidationRuleType.MIN_VALUE,
          value: 50,
          message: "Length must be at least 50 cm",
        },
      ],
    },
    {
      id: "room-width",
      name: "roomWidth",
      label: "Room Width (cm)",
      type: FieldType.NUMBER,
      required: true,
      section: "dimensions",
      order: 2,
      width: "third",
      validation: [
        {
          type: ValidationRuleType.MIN_VALUE,
          value: 50,
          message: "Width must be at least 50 cm",
        },
      ],
    },
    {
      id: "room-height",
      name: "roomHeight",
      label: "Room Height (cm)",
      type: FieldType.NUMBER,
      required: true,
      section: "dimensions",
      order: 3,
      width: "third",
      validation: [
        {
          type: ValidationRuleType.MIN_VALUE,
          value: 200,
          message: "Height must be at least 200 cm",
        },
      ],
    },
    {
      id: "room-area",
      name: "roomArea",
      label: "Room Area (sq m)",
      type: FieldType.CALCULATED,
      required: false,
      section: "dimensions",
      order: 4,
      width: "half",
      readOnly: true,
      calculationFormula:
        "return (values.roomLength * values.roomWidth / 10000).toFixed(2);",
    },
    {
      id: "floor-material",
      name: "floorMaterial",
      label: "Floor Material",
      type: FieldType.SELECT,
      required: true,
      section: "dimensions",
      order: 5,
      width: "half",
      options: [
        { value: "tile", label: "Tile" },
        { value: "wood", label: "Wood" },
        { value: "carpet", label: "Carpet" },
        { value: "vinyl", label: "Vinyl" },
        { value: "concrete", label: "Concrete" },
        { value: "other", label: "Other" },
      ],
    },
    {
      id: "doorways",
      name: "doorways",
      label: "Doorways",
      type: FieldType.REPEATER,
      required: true,
      section: "doorways",
      order: 1,
      width: "full",
      fields: [
        {
          id: "doorway-location",
          name: "doorwayLocation",
          label: "Location",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "doorway-width",
          name: "doorwayWidth",
          label: "Width (cm)",
          type: FieldType.NUMBER,
          required: true,
          width: "third",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 30,
              message: "Width must be at least 30 cm",
            },
          ],
        },
        {
          id: "doorway-threshold-height",
          name: "doorwayThresholdHeight",
          label: "Threshold Height (cm)",
          type: FieldType.NUMBER,
          required: true,
          width: "third",
          defaultValue: 0,
        },
      ],
    },
    {
      id: "windows",
      name: "windows",
      label: "Windows",
      type: FieldType.REPEATER,
      required: false,
      section: "windows",
      order: 1,
      width: "full",
      fields: [
        {
          id: "window-location",
          name: "windowLocation",
          label: "Location",
          type: FieldType.TEXT,
          required: true,
          width: "quarter",
        },
        {
          id: "window-width",
          name: "windowWidth",
          label: "Width (cm)",
          type: FieldType.NUMBER,
          required: true,
          width: "quarter",
        },
        {
          id: "window-height",
          name: "windowHeight",
          label: "Height (cm)",
          type: FieldType.NUMBER,
          required: true,
          width: "quarter",
        },
        {
          id: "window-sill-height",
          name: "windowSillHeight",
          label: "Sill Height (cm)",
          type: FieldType.NUMBER,
          required: true,
          width: "quarter",
        },
      ],
    },
    {
      id: "fixtures",
      name: "fixtures",
      label: "Fixtures & Features",
      type: FieldType.REPEATER,
      required: false,
      section: "fixtures",
      order: 1,
      width: "full",
      fields: [
        {
          id: "fixture-type",
          name: "fixtureType",
          label: "Type",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "sink", label: "Sink" },
            { value: "toilet", label: "Toilet" },
            { value: "shower", label: "Shower" },
            { value: "bathtub", label: "Bathtub" },
            { value: "cabinet", label: "Cabinet" },
            { value: "counter", label: "Counter" },
            { value: "appliance", label: "Appliance" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "fixture-description",
          name: "fixtureDescription",
          label: "Description",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "fixture-dimensions",
          name: "fixtureDimensions",
          label: "Dimensions (cm)",
          type: FieldType.TEXT,
          required: false,
          width: "third",
          placeholder: "e.g., 60x40x85",
        },
      ],
    },
    {
      id: "measurement-notes",
      name: "measurementNotes",
      label: "Measurement Notes",
      type: FieldType.TEXTAREA,
      placeholder: "Enter any additional notes about the measurements",
      required: false,
      section: "fixtures",
      order: 2,
      width: "full",
    },
  ],
  dependencies: [
    {
      formId: "initial-assessment-form",
      description: "Room measurement requires an initial assessment",
      type: "prerequisite",
      required: true,
    },
  ],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

/**
 * Material Selection Form
 * Used for selecting materials for room modifications
 */
export const materialSelectionForm: FormMetadata = {
  id: "material-selection-form",
  title: "Material Selection",
  description: "Select materials for room modifications",
  module: FormModule.ASSESSMENT,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: ["assessor", "supervisor", "admin", "procurement"],
    [FormPermission.CREATE]: ["assessor", "admin"],
    [FormPermission.EDIT]: ["assessor", "admin"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["supervisor", "admin"],
    [FormPermission.REJECT]: ["supervisor", "admin"],
    [FormPermission.SUBMIT]: ["assessor", "admin"],
    [FormPermission.PRINT]: ["assessor", "supervisor", "admin", "procurement"],
    [FormPermission.EXPORT]: ["supervisor", "admin", "procurement"],
  },
  clientTypes: [ClientType.FDF, ClientType.ADHA, ClientType.CASH],
  sections: [
    {
      id: "room-reference",
      title: "Room Reference",
      description: "Reference to the room assessment",
      order: 1,
      collapsible: false,
    },
    {
      id: "flooring-materials",
      title: "Flooring Materials",
      description: "Select flooring materials",
      order: 2,
      collapsible: true,
    },
    {
      id: "wall-materials",
      title: "Wall Materials",
      description: "Select wall materials",
      order: 3,
      collapsible: true,
    },
    {
      id: "fixture-materials",
      title: "Fixture Materials",
      description: "Select materials for fixtures",
      order: 4,
      collapsible: true,
    },
    {
      id: "additional-materials",
      title: "Additional Materials",
      description: "Select any additional materials needed",
      order: 5,
      collapsible: true,
    },
  ],
  fields: [
    {
      id: "room-assessment-id",
      name: "roomAssessmentId",
      label: "Room Assessment",
      type: FieldType.SELECT,
      required: true,
      section: "room-reference",
      order: 1,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/assessments/room/list",
        valueField: "id",
        labelField: "title",
        filters: { status: "approved" },
      },
    },
    {
      id: "flooring-material",
      name: "flooringMaterial",
      label: "Flooring Material",
      type: FieldType.SELECT,
      required: true,
      section: "flooring-materials",
      order: 1,
      width: "half",
      options: [
        { value: "non-slip-tile", label: "Non-Slip Tile" },
        { value: "vinyl", label: "Vinyl Flooring" },
        { value: "rubber", label: "Rubber Flooring" },
        { value: "hardwood", label: "Hardwood" },
        { value: "laminate", label: "Laminate" },
        { value: "carpet", label: "Carpet" },
        { value: "other", label: "Other" },
      ],
    },
    {
      id: "flooring-color",
      name: "flooringColor",
      label: "Flooring Color/Finish",
      type: FieldType.TEXT,
      required: true,
      section: "flooring-materials",
      order: 2,
      width: "half",
    },
    {
      id: "flooring-quantity",
      name: "flooringQuantity",
      label: "Flooring Quantity (sq m)",
      type: FieldType.NUMBER,
      required: true,
      section: "flooring-materials",
      order: 3,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.MIN_VALUE,
          value: 0.1,
          message: "Quantity must be greater than 0",
        },
      ],
    },
    {
      id: "flooring-notes",
      name: "flooringNotes",
      label: "Flooring Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "flooring-materials",
      order: 4,
      width: "full",
    },
    {
      id: "wall-material",
      name: "wallMaterial",
      label: "Wall Material",
      type: FieldType.SELECT,
      required: true,
      section: "wall-materials",
      order: 1,
      width: "half",
      options: [
        { value: "ceramic-tile", label: "Ceramic Tile" },
        { value: "porcelain-tile", label: "Porcelain Tile" },
        { value: "paint", label: "Paint" },
        { value: "wallpaper", label: "Wallpaper" },
        { value: "wood-paneling", label: "Wood Paneling" },
        { value: "other", label: "Other" },
      ],
    },
    {
      id: "wall-color",
      name: "wallColor",
      label: "Wall Color/Finish",
      type: FieldType.TEXT,
      required: true,
      section: "wall-materials",
      order: 2,
      width: "half",
    },
    {
      id: "wall-quantity",
      name: "wallQuantity",
      label: "Wall Material Quantity (sq m)",
      type: FieldType.NUMBER,
      required: true,
      section: "wall-materials",
      order: 3,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.MIN_VALUE,
          value: 0.1,
          message: "Quantity must be greater than 0",
        },
      ],
    },
    {
      id: "wall-notes",
      name: "wallNotes",
      label: "Wall Material Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "wall-materials",
      order: 4,
      width: "full",
    },
    {
      id: "fixtures",
      name: "fixtures",
      label: "Fixtures",
      type: FieldType.REPEATER,
      required: false,
      section: "fixture-materials",
      order: 1,
      width: "full",
      fields: [
        {
          id: "fixture-type",
          name: "fixtureType",
          label: "Fixture Type",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "grab-bar", label: "Grab Bar" },
            { value: "handrail", label: "Handrail" },
            { value: "shower-seat", label: "Shower Seat" },
            { value: "toilet", label: "Toilet" },
            { value: "sink", label: "Sink" },
            { value: "faucet", label: "Faucet" },
            { value: "cabinet", label: "Cabinet" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "fixture-material",
          name: "fixtureMaterial",
          label: "Material",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "fixture-quantity",
          name: "fixtureQuantity",
          label: "Quantity",
          type: FieldType.NUMBER,
          required: true,
          width: "third",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 1,
              message: "Quantity must be at least 1",
            },
          ],
        },
      ],
    },
    {
      id: "fixture-notes",
      name: "fixtureNotes",
      label: "Fixture Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "fixture-materials",
      order: 2,
      width: "full",
    },
    {
      id: "additional-materials",
      name: "additionalMaterials",
      label: "Additional Materials",
      type: FieldType.REPEATER,
      required: false,
      section: "additional-materials",
      order: 1,
      width: "full",
      fields: [
        {
          id: "material-name",
          name: "materialName",
          label: "Material Name",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "material-description",
          name: "materialDescription",
          label: "Description",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "material-quantity",
          name: "materialQuantity",
          label: "Quantity",
          type: FieldType.NUMBER,
          required: true,
          width: "third",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 1,
              message: "Quantity must be at least 1",
            },
          ],
        },
      ],
    },
    {
      id: "material-preferences",
      name: "materialPreferences",
      label: "Material Preferences",
      type: FieldType.TEXTAREA,
      placeholder:
        "Enter any specific preferences or requirements for materials",
      required: false,
      section: "additional-materials",
      order: 2,
      width: "full",
    },
  ],
  dependencies: [
    {
      formId: "room-assessment-form",
      description: "Material selection requires a room assessment",
      type: "prerequisite",
      required: true,
    },
  ],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

/**
 * Modification Plan Form
 * Used for planning detailed modifications for a room
 */
export const modificationPlanForm: FormMetadata = {
  id: "modification-plan-form",
  title: "Modification Plan",
  description: "Detailed plan for room modifications",
  module: FormModule.ASSESSMENT,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: ["assessor", "supervisor", "admin", "contractor"],
    [FormPermission.CREATE]: ["assessor", "admin"],
    [FormPermission.EDIT]: ["assessor", "admin"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["supervisor", "admin"],
    [FormPermission.REJECT]: ["supervisor", "admin"],
    [FormPermission.SUBMIT]: ["assessor", "admin"],
    [FormPermission.PRINT]: ["assessor", "supervisor", "admin", "contractor"],
    [FormPermission.EXPORT]: ["supervisor", "admin", "contractor"],
  },
  clientTypes: [ClientType.FDF, ClientType.ADHA, ClientType.CASH],
  sections: [
    {
      id: "room-reference",
      title: "Room Reference",
      description: "Reference to the room assessment",
      order: 1,
      collapsible: false,
    },
    {
      id: "modification-details",
      title: "Modification Details",
      description: "Details of planned modifications",
      order: 2,
      collapsible: false,
    },
    {
      id: "structural-changes",
      title: "Structural Changes",
      description: "Structural changes required",
      order: 3,
      collapsible: true,
    },
    {
      id: "fixture-installations",
      title: "Fixture Installations",
      description: "Fixtures to be installed",
      order: 4,
      collapsible: true,
    },
    {
      id: "timeline",
      title: "Timeline",
      description: "Timeline for modifications",
      order: 5,
      collapsible: true,
    },
    {
      id: "approvals",
      title: "Approvals",
      description: "Required approvals",
      order: 6,
      collapsible: true,
    },
  ],
  fields: [
    {
      id: "room-assessment-id",
      name: "roomAssessmentId",
      label: "Room Assessment",
      type: FieldType.REFERENCE,
      required: true,
      section: "room-reference",
      order: 1,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/assessments/room/list",
        valueField: "id",
        labelField: "title",
        filters: { status: "approved" },
      },
    },
    {
      id: "modification-summary",
      name: "modificationSummary",
      label: "Modification Summary",
      type: FieldType.TEXTAREA,
      required: true,
      section: "modification-details",
      order: 1,
      width: "full",
      placeholder: "Provide a summary of all planned modifications",
    },
    {
      id: "modification-purpose",
      name: "modificationPurpose",
      label: "Purpose of Modifications",
      type: FieldType.MULTISELECT,
      required: true,
      section: "modification-details",
      order: 2,
      width: "full",
      options: [
        { value: "improve-accessibility", label: "Improve Accessibility" },
        { value: "enhance-safety", label: "Enhance Safety" },
        { value: "increase-independence", label: "Increase Independence" },
        { value: "accommodate-equipment", label: "Accommodate Equipment" },
        { value: "prevent-falls", label: "Prevent Falls" },
        { value: "improve-mobility", label: "Improve Mobility" },
        { value: "other", label: "Other" },
      ],
    },
    {
      id: "priority-level",
      name: "priorityLevel",
      label: "Priority Level",
      type: FieldType.SELECT,
      required: true,
      section: "modification-details",
      order: 3,
      width: "half",
      options: [
        { value: "critical", label: "Critical - Immediate action required" },
        { value: "high", label: "High - Action required within 1 month" },
        { value: "medium", label: "Medium - Action required within 3 months" },
        { value: "low", label: "Low - Action can be scheduled later" },
      ],
    },
    {
      id: "structural-changes-required",
      name: "structuralChangesRequired",
      label: "Structural Changes Required",
      type: FieldType.CHECKBOX,
      required: true,
      section: "structural-changes",
      order: 1,
      width: "full",
    },
    {
      id: "structural-change-types",
      name: "structuralChangeTypes",
      label: "Types of Structural Changes",
      type: FieldType.MULTISELECT,
      required: false,
      section: "structural-changes",
      order: 2,
      width: "full",
      options: [
        { value: "wall-removal", label: "Wall Removal" },
        { value: "doorway-widening", label: "Doorway Widening" },
        { value: "floor-leveling", label: "Floor Leveling" },
        { value: "ramp-installation", label: "Ramp Installation" },
        { value: "ceiling-reinforcement", label: "Ceiling Reinforcement" },
        {
          value: "electrical-modifications",
          label: "Electrical Modifications",
        },
        { value: "plumbing-modifications", label: "Plumbing Modifications" },
        { value: "other", label: "Other" },
      ],
      conditional: {
        field: "structural-changes-required",
        operator: "equals",
        value: true,
      },
    },
    {
      id: "structural-change-details",
      name: "structuralChangeDetails",
      label: "Structural Change Details",
      type: FieldType.TEXTAREA,
      required: false,
      section: "structural-changes",
      order: 3,
      width: "full",
      placeholder: "Provide detailed specifications for structural changes",
      conditional: {
        field: "structural-changes-required",
        operator: "equals",
        value: true,
      },
    },
    {
      id: "fixtures",
      name: "fixtures",
      label: "Fixtures to Install",
      type: FieldType.REPEATER,
      required: false,
      section: "fixture-installations",
      order: 1,
      width: "full",
      fields: [
        {
          id: "fixture-type",
          name: "fixtureType",
          label: "Fixture Type",
          type: FieldType.SELECT,
          required: true,
          width: "third",
          options: [
            { value: "grab-bar", label: "Grab Bar" },
            { value: "handrail", label: "Handrail" },
            { value: "shower-seat", label: "Shower Seat" },
            { value: "toilet", label: "Toilet" },
            { value: "sink", label: "Sink" },
            { value: "faucet", label: "Faucet" },
            { value: "cabinet", label: "Cabinet" },
            { value: "lighting", label: "Lighting" },
            { value: "switch", label: "Switch/Control" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "fixture-location",
          name: "fixtureLocation",
          label: "Location",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "fixture-specifications",
          name: "fixtureSpecifications",
          label: "Specifications",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
      ],
    },
    {
      id: "fixture-notes",
      name: "fixtureNotes",
      label: "Fixture Installation Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "fixture-installations",
      order: 2,
      width: "full",
    },
    {
      id: "estimated-start-date",
      name: "estimatedStartDate",
      label: "Estimated Start Date",
      type: FieldType.DATE,
      required: true,
      section: "timeline",
      order: 1,
      width: "half",
    },
    {
      id: "estimated-completion-date",
      name: "estimatedCompletionDate",
      label: "Estimated Completion Date",
      type: FieldType.DATE,
      required: true,
      section: "timeline",
      order: 2,
      width: "half",
    },
    {
      id: "estimated-duration-days",
      name: "estimatedDurationDays",
      label: "Estimated Duration (Days)",
      type: FieldType.NUMBER,
      required: true,
      section: "timeline",
      order: 3,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.MIN_VALUE,
          value: 1,
          message: "Duration must be at least 1 day",
        },
      ],
    },
    {
      id: "phased-implementation",
      name: "phasedImplementation",
      label: "Phased Implementation",
      type: FieldType.CHECKBOX,
      required: true,
      section: "timeline",
      order: 4,
      width: "half",
    },
    {
      id: "phase-details",
      name: "phaseDetails",
      label: "Phase Details",
      type: FieldType.TEXTAREA,
      required: false,
      section: "timeline",
      order: 5,
      width: "full",
      conditional: {
        field: "phased-implementation",
        operator: "equals",
        value: true,
      },
    },
    {
      id: "building-permit-required",
      name: "buildingPermitRequired",
      label: "Building Permit Required",
      type: FieldType.CHECKBOX,
      required: true,
      section: "approvals",
      order: 1,
      width: "half",
    },
    {
      id: "hoa-approval-required",
      name: "hoaApprovalRequired",
      label: "HOA Approval Required",
      type: FieldType.CHECKBOX,
      required: true,
      section: "approvals",
      order: 2,
      width: "half",
    },
    {
      id: "approval-notes",
      name: "approvalNotes",
      label: "Approval Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "approvals",
      order: 3,
      width: "full",
    },
  ],
  dependencies: [
    {
      formId: "room-assessment-form",
      description: "Modification plan requires a room assessment",
      type: "prerequisite",
      required: true,
    },
  ],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

/**
 * Cost Estimation Form
 * Used for estimating costs for room modifications
 */
export const costEstimationForm: FormMetadata = {
  id: "cost-estimation-form",
  title: "Cost Estimation",
  description: "Detailed cost estimation for room modifications",
  module: FormModule.ASSESSMENT,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: ["assessor", "supervisor", "admin", "finance"],
    [FormPermission.CREATE]: ["assessor", "admin"],
    [FormPermission.EDIT]: ["assessor", "admin"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["supervisor", "admin"],
    [FormPermission.REJECT]: ["supervisor", "admin"],
    [FormPermission.SUBMIT]: ["assessor", "admin"],
    [FormPermission.PRINT]: ["assessor", "supervisor", "admin", "finance"],
    [FormPermission.EXPORT]: ["supervisor", "admin", "finance"],
  },
  clientTypes: [ClientType.FDF, ClientType.ADHA, ClientType.CASH],
  sections: [
    {
      id: "project-reference",
      title: "Project Reference",
      description: "Reference to the modification plan",
      order: 1,
      collapsible: false,
    },
    {
      id: "labor-costs",
      title: "Labor Costs",
      description: "Estimated labor costs",
      order: 2,
      collapsible: true,
    },
    {
      id: "material-costs",
      title: "Material Costs",
      description: "Estimated material costs",
      order: 3,
      collapsible: true,
    },
    {
      id: "equipment-costs",
      title: "Equipment Costs",
      description: "Estimated equipment costs",
      order: 4,
      collapsible: true,
    },
    {
      id: "additional-costs",
      title: "Additional Costs",
      description: "Additional costs and fees",
      order: 5,
      collapsible: true,
    },
    {
      id: "cost-summary",
      title: "Cost Summary",
      description: "Summary of all costs",
      order: 6,
      collapsible: false,
    },
  ],
  fields: [
    {
      id: "modification-plan-id",
      name: "modificationPlanId",
      label: "Modification Plan",
      type: FieldType.REFERENCE,
      required: true,
      section: "project-reference",
      order: 1,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/modifications/plans/list",
        valueField: "id",
        labelField: "title",
        filters: { status: "approved" },
      },
    },
    {
      id: "estimation-date",
      name: "estimationDate",
      label: "Estimation Date",
      type: FieldType.DATE,
      required: true,
      section: "project-reference",
      order: 2,
      width: "half",
      defaultValue: new Date().toISOString().split("T")[0],
    },
    {
      id: "estimator-id",
      name: "estimatorId",
      label: "Estimator",
      type: FieldType.SELECT,
      required: true,
      section: "project-reference",
      order: 3,
      width: "half",
      dataSource: {
        type: "api",
        source: "/api/users/estimators",
        valueField: "id",
        labelField: "fullName",
        filters: { active: true },
      },
    },
    {
      id: "currency",
      name: "currency",
      label: "Currency",
      type: FieldType.SELECT,
      required: true,
      section: "project-reference",
      order: 4,
      width: "half",
      options: [
        { value: "SAR", label: "Saudi Riyal (SAR)" },
        { value: "USD", label: "US Dollar (USD)" },
      ],
      defaultValue: "SAR",
    },
    {
      id: "labor-items",
      name: "laborItems",
      label: "Labor Items",
      type: FieldType.REPEATER,
      required: true,
      section: "labor-costs",
      order: 1,
      width: "full",
      fields: [
        {
          id: "labor-description",
          name: "laborDescription",
          label: "Description",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "labor-hours",
          name: "laborHours",
          label: "Hours",
          type: FieldType.NUMBER,
          required: true,
          width: "sixth",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 0.5,
              message: "Hours must be at least 0.5",
            },
          ],
        },
        {
          id: "labor-rate",
          name: "laborRate",
          label: "Hourly Rate",
          type: FieldType.NUMBER,
          required: true,
          width: "sixth",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 1,
              message: "Rate must be at least 1",
            },
          ],
        },
        {
          id: "labor-cost",
          name: "laborCost",
          label: "Cost",
          type: FieldType.CALCULATED,
          required: true,
          width: "sixth",
          readOnly: true,
          calculationFormula:
            "return (values.laborHours * values.laborRate).toFixed(2);",
        },
        {
          id: "labor-notes",
          name: "laborNotes",
          label: "Notes",
          type: FieldType.TEXT,
          required: false,
          width: "third",
        },
      ],
    },
    {
      id: "labor-subtotal",
      name: "laborSubtotal",
      label: "Labor Subtotal",
      type: FieldType.CALCULATED,
      required: true,
      section: "labor-costs",
      order: 2,
      width: "half",
      readOnly: true,
      calculationFormula:
        "return values.laborItems ? values.laborItems.reduce((sum, item) => sum + (parseFloat(item.laborCost) || 0), 0).toFixed(2) : '0.00';",
    },
    {
      id: "material-items",
      name: "materialItems",
      label: "Material Items",
      type: FieldType.REPEATER,
      required: true,
      section: "material-costs",
      order: 1,
      width: "full",
      fields: [
        {
          id: "material-description",
          name: "materialDescription",
          label: "Description",
          type: FieldType.TEXT,
          required: true,
          width: "quarter",
        },
        {
          id: "material-quantity",
          name: "materialQuantity",
          label: "Quantity",
          type: FieldType.NUMBER,
          required: true,
          width: "sixth",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 0.1,
              message: "Quantity must be at least 0.1",
            },
          ],
        },
        {
          id: "material-unit",
          name: "materialUnit",
          label: "Unit",
          type: FieldType.TEXT,
          required: true,
          width: "sixth",
        },
        {
          id: "material-unit-price",
          name: "materialUnitPrice",
          label: "Unit Price",
          type: FieldType.NUMBER,
          required: true,
          width: "sixth",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 0.01,
              message: "Price must be at least 0.01",
            },
          ],
        },
        {
          id: "material-cost",
          name: "materialCost",
          label: "Cost",
          type: FieldType.CALCULATED,
          required: true,
          width: "sixth",
          readOnly: true,
          calculationFormula:
            "return (values.materialQuantity * values.materialUnitPrice).toFixed(2);",
        },
      ],
    },
    {
      id: "material-subtotal",
      name: "materialSubtotal",
      label: "Material Subtotal",
      type: FieldType.CALCULATED,
      required: true,
      section: "material-costs",
      order: 2,
      width: "half",
      readOnly: true,
      calculationFormula:
        "return values.materialItems ? values.materialItems.reduce((sum, item) => sum + (parseFloat(item.materialCost) || 0), 0).toFixed(2) : '0.00';",
    },
    {
      id: "equipment-items",
      name: "equipmentItems",
      label: "Equipment Items",
      type: FieldType.REPEATER,
      required: false,
      section: "equipment-costs",
      order: 1,
      width: "full",
      fields: [
        {
          id: "equipment-description",
          name: "equipmentDescription",
          label: "Description",
          type: FieldType.TEXT,
          required: true,
          width: "third",
        },
        {
          id: "equipment-quantity",
          name: "equipmentQuantity",
          label: "Quantity",
          type: FieldType.NUMBER,
          required: true,
          width: "sixth",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 1,
              message: "Quantity must be at least 1",
            },
          ],
        },
        {
          id: "equipment-unit-price",
          name: "equipmentUnitPrice",
          label: "Unit Price",
          type: FieldType.NUMBER,
          required: true,
          width: "sixth",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 0.01,
              message: "Price must be at least 0.01",
            },
          ],
        },
        {
          id: "equipment-cost",
          name: "equipmentCost",
          label: "Cost",
          type: FieldType.CALCULATED,
          required: true,
          width: "sixth",
          readOnly: true,
          calculationFormula:
            "return (values.equipmentQuantity * values.equipmentUnitPrice).toFixed(2);",
        },
        {
          id: "equipment-notes",
          name: "equipmentNotes",
          label: "Notes",
          type: FieldType.TEXT,
          required: false,
          width: "third",
        },
      ],
    },
    {
      id: "equipment-subtotal",
      name: "equipmentSubtotal",
      label: "Equipment Subtotal",
      type: FieldType.CALCULATED,
      required: true,
      section: "equipment-costs",
      order: 2,
      width: "half",
      readOnly: true,
      calculationFormula:
        "return values.equipmentItems ? values.equipmentItems.reduce((sum, item) => sum + (parseFloat(item.equipmentCost) || 0), 0).toFixed(2) : '0.00';",
    },
    {
      id: "additional-items",
      name: "additionalItems",
      label: "Additional Items",
      type: FieldType.REPEATER,
      required: false,
      section: "additional-costs",
      order: 1,
      width: "full",
      fields: [
        {
          id: "additional-description",
          name: "additionalDescription",
          label: "Description",
          type: FieldType.TEXT,
          required: true,
          width: "half",
        },
        {
          id: "additional-cost",
          name: "additionalCost",
          label: "Cost",
          type: FieldType.NUMBER,
          required: true,
          width: "quarter",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 0.01,
              message: "Cost must be at least 0.01",
            },
          ],
        },
        {
          id: "additional-notes",
          name: "additionalNotes",
          label: "Notes",
          type: FieldType.TEXT,
          required: false,
          width: "quarter",
        },
      ],
    },
    {
      id: "additional-subtotal",
      name: "additionalSubtotal",
      label: "Additional Costs Subtotal",
      type: FieldType.CALCULATED,
      required: true,
      section: "additional-costs",
      order: 2,
      width: "half",
      readOnly: true,
      calculationFormula:
        "return values.additionalItems ? values.additionalItems.reduce((sum, item) => sum + (parseFloat(item.additionalCost) || 0), 0).toFixed(2) : '0.00';",
    },
    {
      id: "subtotal",
      name: "subtotal",
      label: "Subtotal",
      type: FieldType.CALCULATED,
      required: true,
      section: "cost-summary",
      order: 1,
      width: "half",
      readOnly: true,
      calculationFormula:
        "return (parseFloat(values.laborSubtotal || 0) + parseFloat(values.materialSubtotal || 0) + parseFloat(values.equipmentSubtotal || 0) + parseFloat(values.additionalSubtotal || 0)).toFixed(2);",
    },
    {
      id: "contingency-percentage",
      name: "contingencyPercentage",
      label: "Contingency Percentage",
      type: FieldType.NUMBER,
      required: true,
      section: "cost-summary",
      order: 2,
      width: "half",
      defaultValue: 10,
      validation: [
        {
          type: ValidationRuleType.MIN_VALUE,
          value: 0,
          message: "Percentage must be at least 0",
        },
        {
          type: ValidationRuleType.MAX_VALUE,
          value: 100,
          message: "Percentage cannot exceed 100",
        },
      ],
    },
    {
      id: "contingency-amount",
      name: "contingencyAmount",
      label: "Contingency Amount",
      type: FieldType.CALCULATED,
      required: true,
      section: "cost-summary",
      order: 3,
      width: "half",
      readOnly: true,
      calculationFormula:
        "return ((parseFloat(values.subtotal || 0) * parseFloat(values.contingencyPercentage || 0)) / 100).toFixed(2);",
    },
    {
      id: "tax-percentage",
      name: "taxPercentage",
      label: "Tax Percentage",
      type: FieldType.NUMBER,
      required: true,
      section: "cost-summary",
      order: 4,
      width: "half",
      defaultValue: 15,
      validation: [
        {
          type: ValidationRuleType.MIN_VALUE,
          value: 0,
          message: "Percentage must be at least 0",
        },
        {
          type: ValidationRuleType.MAX_VALUE,
          value: 100,
          message: "Percentage cannot exceed 100",
        },
      ],
    },
    {
      id: "tax-amount",
      name: "taxAmount",
      label: "Tax Amount",
      type: FieldType.CALCULATED,
      required: true,
      section: "cost-summary",
      order: 5,
      width: "half",
      readOnly: true,
      calculationFormula:
        "return ((parseFloat(values.subtotal || 0) * parseFloat(values.taxPercentage || 0)) / 100).toFixed(2);",
    },
    {
      id: "total-cost",
      name: "totalCost",
      label: "Total Cost",
      type: FieldType.CALCULATED,
      required: true,
      section: "cost-summary",
      order: 6,
      width: "half",
      readOnly: true,
      calculationFormula:
        "return (parseFloat(values.subtotal || 0) + parseFloat(values.contingencyAmount || 0) + parseFloat(values.taxAmount || 0)).toFixed(2);",
    },
    {
      id: "cost-notes",
      name: "costNotes",
      label: "Cost Estimation Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "cost-summary",
      order: 7,
      width: "full",
      placeholder: "Add any additional notes about the cost estimation...",
    },
  ],
  dependencies: [
    {
      formId: "modification-plan-form",
      description: "Cost estimation requires a modification plan",
      type: "prerequisite",
      required: true,
    },
  ],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

/**
 * Material Alternatives Form
 * Used for documenting alternative materials for room modifications
 */
export const materialAlternativesForm: FormMetadata = {
  id: "material-alternatives-form",
  title: "Material Alternatives",
  description: "Alternative materials options for room modifications",
  module: FormModule.ASSESSMENT,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: ["assessor", "supervisor", "admin", "procurement"],
    [FormPermission.CREATE]: ["assessor", "admin"],
    [FormPermission.EDIT]: ["assessor", "admin"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["supervisor", "admin"],
    [FormPermission.REJECT]: ["supervisor", "admin"],
    [FormPermission.SUBMIT]: ["assessor", "admin"],
    [FormPermission.PRINT]: ["assessor", "supervisor", "admin", "procurement"],
    [FormPermission.EXPORT]: ["supervisor", "admin", "procurement"],
  },
  clientTypes: [ClientType.FDF, ClientType.ADHA, ClientType.CASH],
  sections: [
    {
      id: "material-selection-reference",
      title: "Material Selection Reference",
      description: "Reference to the material selection form",
      order: 1,
      collapsible: false,
    },
    {
      id: "flooring-alternatives",
      title: "Flooring Alternatives",
      description: "Alternative flooring materials",
      order: 2,
      collapsible: true,
    },
    {
      id: "wall-alternatives",
      title: "Wall Alternatives",
      description: "Alternative wall materials",
      order: 3,
      collapsible: true,
    },
    {
      id: "fixture-alternatives",
      title: "Fixture Alternatives",
      description: "Alternative fixtures",
      order: 4,
      collapsible: true,
    },
    {
      id: "comparison-summary",
      title: "Comparison Summary",
      description: "Summary of alternatives and recommendations",
      order: 5,
      collapsible: false,
    },
  ],
  fields: [
    {
      id: "material-selection-id",
      name: "materialSelectionId",
      label: "Material Selection Reference",
      type: FieldType.REFERENCE,
      required: true,
      section: "material-selection-reference",
      order: 1,
      width: "full",
      dataSource: {
        type: "api",
        source: "/api/assessments/material-selection/list",
        valueField: "id",
        labelField: "title",
        filters: { status: "approved" },
      },
    },
    {
      id: "alternative-reason",
      name: "alternativeReason",
      label: "Reason for Alternatives",
      type: FieldType.MULTISELECT,
      required: true,
      section: "material-selection-reference",
      order: 2,
      width: "full",
      options: [
        { value: "cost-reduction", label: "Cost Reduction" },
        { value: "availability", label: "Material Availability" },
        { value: "client-preference", label: "Client Preference" },
        { value: "durability", label: "Improved Durability" },
        { value: "maintenance", label: "Easier Maintenance" },
        { value: "sustainability", label: "Sustainability" },
        { value: "other", label: "Other" },
      ],
    },
    {
      id: "flooring-alternatives",
      name: "flooringAlternatives",
      label: "Flooring Alternatives",
      type: FieldType.REPEATER,
      required: false,
      section: "flooring-alternatives",
      order: 1,
      width: "full",
      fields: [
        {
          id: "alternative-flooring-material",
          name: "alternativeFlooringMaterial",
          label: "Alternative Material",
          type: FieldType.SELECT,
          required: true,
          width: "quarter",
          options: [
            { value: "vinyl", label: "Vinyl Flooring" },
            { value: "ceramic-tile", label: "Ceramic Tile" },
            { value: "porcelain-tile", label: "Porcelain Tile" },
            { value: "rubber", label: "Rubber Flooring" },
            { value: "laminate", label: "Laminate" },
            { value: "engineered-wood", label: "Engineered Wood" },
            { value: "cork", label: "Cork" },
            { value: "concrete", label: "Polished Concrete" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "alternative-flooring-color",
          name: "alternativeFlooringColor",
          label: "Color/Finish",
          type: FieldType.TEXT,
          required: true,
          width: "quarter",
        },
        {
          id: "alternative-flooring-cost",
          name: "alternativeFlooringCost",
          label: "Cost per sq m",
          type: FieldType.NUMBER,
          required: true,
          width: "quarter",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 0.01,
              message: "Cost must be at least 0.01",
            },
          ],
        },
        {
          id: "alternative-flooring-advantages",
          name: "alternativeFlooringAdvantages",
          label: "Advantages",
          type: FieldType.TEXT,
          required: true,
          width: "quarter",
        },
      ],
    },
    {
      id: "flooring-alternatives-notes",
      name: "flooringAlternativesNotes",
      label: "Flooring Alternatives Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "flooring-alternatives",
      order: 2,
      width: "full",
    },
    {
      id: "wall-alternatives",
      name: "wallAlternatives",
      label: "Wall Alternatives",
      type: FieldType.REPEATER,
      required: false,
      section: "wall-alternatives",
      order: 1,
      width: "full",
      fields: [
        {
          id: "alternative-wall-material",
          name: "alternativeWallMaterial",
          label: "Alternative Material",
          type: FieldType.SELECT,
          required: true,
          width: "quarter",
          options: [
            { value: "ceramic-tile", label: "Ceramic Tile" },
            { value: "porcelain-tile", label: "Porcelain Tile" },
            { value: "vinyl-wallcovering", label: "Vinyl Wallcovering" },
            { value: "paint", label: "Paint" },
            { value: "fiberglass-panels", label: "Fiberglass Panels" },
            { value: "acrylic-panels", label: "Acrylic Panels" },
            { value: "pvc-panels", label: "PVC Panels" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "alternative-wall-color",
          name: "alternativeWallColor",
          label: "Color/Finish",
          type: FieldType.TEXT,
          required: true,
          width: "quarter",
        },
        {
          id: "alternative-wall-cost",
          name: "alternativeWallCost",
          label: "Cost per sq m",
          type: FieldType.NUMBER,
          required: true,
          width: "quarter",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 0.01,
              message: "Cost must be at least 0.01",
            },
          ],
        },
        {
          id: "alternative-wall-advantages",
          name: "alternativeWallAdvantages",
          label: "Advantages",
          type: FieldType.TEXT,
          required: true,
          width: "quarter",
        },
      ],
    },
    {
      id: "wall-alternatives-notes",
      name: "wallAlternativesNotes",
      label: "Wall Alternatives Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "wall-alternatives",
      order: 2,
      width: "full",
    },
    {
      id: "fixture-alternatives",
      name: "fixtureAlternatives",
      label: "Fixture Alternatives",
      type: FieldType.REPEATER,
      required: false,
      section: "fixture-alternatives",
      order: 1,
      width: "full",
      fields: [
        {
          id: "original-fixture-type",
          name: "originalFixtureType",
          label: "Original Fixture Type",
          type: FieldType.SELECT,
          required: true,
          width: "sixth",
          options: [
            { value: "grab-bar", label: "Grab Bar" },
            { value: "handrail", label: "Handrail" },
            { value: "shower-seat", label: "Shower Seat" },
            { value: "toilet", label: "Toilet" },
            { value: "sink", label: "Sink" },
            { value: "faucet", label: "Faucet" },
            { value: "cabinet", label: "Cabinet" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "alternative-fixture-description",
          name: "alternativeFixtureDescription",
          label: "Alternative Description",
          type: FieldType.TEXT,
          required: true,
          width: "sixth",
        },
        {
          id: "alternative-fixture-brand",
          name: "alternativeFixtureBrand",
          label: "Brand/Manufacturer",
          type: FieldType.TEXT,
          required: false,
          width: "sixth",
        },
        {
          id: "alternative-fixture-model",
          name: "alternativeFixtureModel",
          label: "Model",
          type: FieldType.TEXT,
          required: false,
          width: "sixth",
        },
        {
          id: "alternative-fixture-cost",
          name: "alternativeFixtureCost",
          label: "Cost",
          type: FieldType.NUMBER,
          required: true,
          width: "sixth",
          validation: [
            {
              type: ValidationRuleType.MIN_VALUE,
              value: 0.01,
              message: "Cost must be at least 0.01",
            },
          ],
        },
        {
          id: "alternative-fixture-advantages",
          name: "alternativeFixtureAdvantages",
          label: "Advantages",
          type: FieldType.TEXT,
          required: true,
          width: "sixth",
        },
      ],
    },
    {
      id: "fixture-alternatives-notes",
      name: "fixtureAlternativesNotes",
      label: "Fixture Alternatives Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "fixture-alternatives",
      order: 2,
      width: "full",
    },
    {
      id: "cost-impact",
      name: "costImpact",
      label: "Overall Cost Impact",
      type: FieldType.SELECT,
      required: true,
      section: "comparison-summary",
      order: 1,
      width: "half",
      options: [
        { value: "significant-savings", label: "Significant Savings (>20%)" },
        { value: "moderate-savings", label: "Moderate Savings (10-20%)" },
        { value: "minor-savings", label: "Minor Savings (<10%)" },
        { value: "neutral", label: "Neutral (No Significant Change)" },
        { value: "minor-increase", label: "Minor Increase (<10%)" },
        { value: "moderate-increase", label: "Moderate Increase (10-20%)" },
        { value: "significant-increase", label: "Significant Increase (>20%)" },
      ],
    },
    {
      id: "quality-impact",
      name: "qualityImpact",
      label: "Quality Impact",
      type: FieldType.SELECT,
      required: true,
      section: "comparison-summary",
      order: 2,
      width: "half",
      options: [
        { value: "significant-improvement", label: "Significant Improvement" },
        { value: "moderate-improvement", label: "Moderate Improvement" },
        { value: "slight-improvement", label: "Slight Improvement" },
        { value: "neutral", label: "Neutral" },
        { value: "slight-reduction", label: "Slight Reduction" },
        { value: "moderate-reduction", label: "Moderate Reduction" },
        { value: "significant-reduction", label: "Significant Reduction" },
      ],
    },
    {
      id: "recommended-alternatives",
      name: "recommendedAlternatives",
      label: "Recommended Alternatives",
      type: FieldType.TEXTAREA,
      required: true,
      section: "comparison-summary",
      order: 3,
      width: "full",
      placeholder: "Summarize which alternatives are recommended and why...",
    },
    {
      id: "client-approval-required",
      name: "clientApprovalRequired",
      label: "Client Approval Required",
      type: FieldType.CHECKBOX,
      required: true,
      section: "comparison-summary",
      order: 4,
      width: "half",
    },
    {
      id: "alternatives-notes",
      name: "alternativesNotes",
      label: "Additional Notes",
      type: FieldType.TEXTAREA,
      required: false,
      section: "comparison-summary",
      order: 5,
      width: "full",
    },
  ],
  dependencies: [
    {
      formId: "material-selection-form",
      description: "Material alternatives requires a material selection form",
      type: "prerequisite",
      required: true,
    },
  ],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

// Register forms with the form registry
formRegistry.registerForm(
  {
    id: roomMeasurementForm.id,
    title: roomMeasurementForm.title,
    description: roomMeasurementForm.description,
    module: roomMeasurementForm.module,
    clientTypes: roomMeasurementForm.clientTypes,
    permissions: roomMeasurementForm.permissions,
    dependencies: roomMeasurementForm.dependencies,
    version: roomMeasurementForm.version,
    path: "/assessments/room-measurement",
    icon: "ruler",
    isActive: true,
  },
  roomMeasurementForm,
);

formRegistry.registerForm(
  {
    id: materialSelectionForm.id,
    title: materialSelectionForm.title,
    description: materialSelectionForm.description,
    module: materialSelectionForm.module,
    clientTypes: materialSelectionForm.clientTypes,
    permissions: materialSelectionForm.permissions,
    dependencies: materialSelectionForm.dependencies,
    version: materialSelectionForm.version,
    path: "/assessments/material-selection",
    icon: "package",
    isActive: true,
  },
  materialSelectionForm,
);

formRegistry.registerForm(
  {
    id: modificationPlanForm.id,
    title: modificationPlanForm.title,
    description: modificationPlanForm.description,
    module: modificationPlanForm.module,
    clientTypes: modificationPlanForm.clientTypes,
    permissions: modificationPlanForm.permissions,
    dependencies: modificationPlanForm.dependencies,
    version: modificationPlanForm.version,
    path: "/assessments/modification-plan",
    icon: "clipboard-list",
    isActive: true,
  },
  modificationPlanForm,
);

formRegistry.registerForm(
  {
    id: costEstimationForm.id,
    title: costEstimationForm.title,
    description: costEstimationForm.description,
    module: costEstimationForm.module,
    clientTypes: costEstimationForm.clientTypes,
    permissions: costEstimationForm.permissions,
    dependencies: costEstimationForm.dependencies,
    version: costEstimationForm.version,
    path: "/assessments/cost-estimation",
    icon: "calculator",
    isActive: true,
  },
  costEstimationForm,
);

formRegistry.registerForm(
  {
    id: materialAlternativesForm.id,
    title: materialAlternativesForm.title,
    description: materialAlternativesForm.description,
    module: materialAlternativesForm.module,
    clientTypes: materialAlternativesForm.clientTypes,
    permissions: materialAlternativesForm.permissions,
    dependencies: materialAlternativesForm.dependencies,
    version: materialAlternativesForm.version,
    path: "/assessments/material-alternatives",
    icon: "git-compare",
    isActive: true,
  },
  materialAlternativesForm,
);
