import {
  ClientType,
  FieldType,
  FormMetadata,
  FormModule,
  FormPermission,
  ValidationRuleType,
} from "../types";
import { formRegistry } from "../registry";

/**
 * Supplier Performance Evaluation Form (F15.2)
 * Used to evaluate the performance of suppliers
 */
export const supplierPerformance: FormMetadata = {
  id: "supplier-performance-form",
  title: "Supplier Performance Evaluation",
  description: "Evaluate the performance of suppliers",
  module: FormModule.SUPPLIER,
  version: "1.0.0",
  permissions: {
    [FormPermission.VIEW]: [
      "admin",
      "manager",
      "procurement-officer",
      "finance-officer",
    ],
    [FormPermission.CREATE]: ["admin", "manager", "procurement-officer"],
    [FormPermission.EDIT]: ["admin", "manager", "procurement-officer"],
    [FormPermission.DELETE]: ["admin"],
    [FormPermission.APPROVE]: ["admin", "manager"],
    [FormPermission.REJECT]: ["admin", "manager"],
    [FormPermission.SUBMIT]: ["admin", "manager", "procurement-officer"],
    [FormPermission.PRINT]: [
      "admin",
      "manager",
      "procurement-officer",
      "finance-officer",
    ],
    [FormPermission.EXPORT]: ["admin", "manager"],
  },
  clientTypes: [
    ClientType.FDF,
    ClientType.ADHA,
    ClientType.CASH,
    ClientType.OTHER,
  ],
  sections: [
    {
      id: "evaluation-information",
      title: "Evaluation Information",
      description: "Basic information about the evaluation",
      order: 1,
      collapsible: false,
    },
    {
      id: "supplier-details",
      title: "Supplier Details",
      description: "Information about the supplier being evaluated",
      order: 2,
      collapsible: false,
    },
    {
      id: "performance-criteria",
      title: "Performance Criteria",
      description: "Evaluation of supplier performance across key areas",
      order: 3,
      collapsible: false,
    },
    {
      id: "quality-assessment",
      title: "Quality Assessment",
      description: "Evaluation of product/service quality",
      order: 4,
      collapsible: false,
    },
    {
      id: "delivery-assessment",
      title: "Delivery Assessment",
      description: "Evaluation of delivery performance",
      order: 5,
      collapsible: false,
    },
    {
      id: "overall-evaluation",
      title: "Overall Evaluation",
      description: "Summary evaluation and recommendations",
      order: 6,
      collapsible: false,
    },
    {
      id: "documentation",
      title: "Documentation",
      description: "Supporting documents for the evaluation",
      order: 7,
      collapsible: true,
    },
  ],
  fields: [
    {
      id: "evaluation-id",
      name: "evaluationId",
      label: "Evaluation ID",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "evaluation-information",
      order: 1,
      width: "half",
      helpText: "Unique identifier for the evaluation",
    },
    {
      id: "evaluation-date",
      name: "evaluationDate",
      label: "Evaluation Date",
      type: FieldType.DATE,
      required: true,
      section: "evaluation-information",
      order: 2,
      width: "half",
      defaultValue: new Date().toISOString().split("T")[0],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Evaluation date is required",
        },
      ],
    },
    {
      id: "evaluation-period-start",
      name: "evaluationPeriodStart",
      label: "Evaluation Period Start",
      type: FieldType.DATE,
      required: true,
      section: "evaluation-information",
      order: 3,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Evaluation period start date is required",
        },
      ],
    },
    {
      id: "evaluation-period-end",
      name: "evaluationPeriodEnd",
      label: "Evaluation Period End",
      type: FieldType.DATE,
      required: true,
      section: "evaluation-information",
      order: 4,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Evaluation period end date is required",
        },
        {
          type: ValidationRuleType.CUSTOM,
          value: (value: string, formData: any) => {
            if (!value || !formData.evaluationPeriodStart) return true;
            const endDate = new Date(value);
            const startDate = new Date(formData.evaluationPeriodStart);
            return endDate >= startDate;
          },
          message: "End date must be after or equal to start date",
        },
      ],
    },
    {
      id: "evaluator-name",
      name: "evaluatorName",
      label: "Evaluator Name",
      type: FieldType.TEXT,
      required: true,
      section: "evaluation-information",
      order: 5,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Evaluator name is required",
        },
      ],
    },
    {
      id: "evaluator-position",
      name: "evaluatorPosition",
      label: "Evaluator Position",
      type: FieldType.TEXT,
      required: true,
      section: "evaluation-information",
      order: 6,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Evaluator position is required",
        },
      ],
    },
    {
      id: "supplier-id",
      name: "supplierId",
      label: "Supplier ID",
      type: FieldType.TEXT,
      readOnly: true,
      required: true,
      section: "supplier-details",
      order: 1,
      width: "half",
      helpText: "Unique identifier for the supplier",
    },
    {
      id: "supplier-name",
      name: "supplierName",
      label: "Supplier Name",
      type: FieldType.TEXT,
      required: true,
      section: "supplier-details",
      order: 2,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Supplier name is required",
        },
      ],
    },
    {
      id: "supplier-type",
      name: "supplierType",
      label: "Supplier Type",
      type: FieldType.SELECT,
      required: true,
      section: "supplier-details",
      order: 3,
      width: "half",
      options: [
        { value: "materials", label: "Materials Supplier" },
        { value: "equipment", label: "Equipment Supplier" },
        { value: "services", label: "Service Provider" },
        { value: "contractor", label: "Contractor" },
        { value: "consultant", label: "Consultant" },
        { value: "other", label: "Other" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Supplier type is required",
        },
      ],
    },
    {
      id: "products-services",
      name: "productsServices",
      label: "Products/Services Provided",
      type: FieldType.TEXTAREA,
      required: true,
      section: "supplier-details",
      order: 4,
      width: "half",
      placeholder:
        "List the main products or services provided by this supplier",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Products/services information is required",
        },
      ],
    },
    {
      id: "contract-reference",
      name: "contractReference",
      label: "Contract Reference",
      type: FieldType.TEXT,
      required: false,
      section: "supplier-details",
      order: 5,
      width: "half",
      helpText: "Reference number of the contract, if applicable",
    },
    {
      id: "relationship-duration",
      name: "relationshipDuration",
      label: "Relationship Duration",
      type: FieldType.SELECT,
      required: true,
      section: "supplier-details",
      order: 6,
      width: "half",
      options: [
        { value: "less-than-1", label: "Less than 1 year" },
        { value: "1-3", label: "1-3 years" },
        { value: "3-5", label: "3-5 years" },
        { value: "more-than-5", label: "More than 5 years" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Relationship duration is required",
        },
      ],
    },
    {
      id: "timeliness",
      name: "timeliness",
      label: "Timeliness",
      type: FieldType.RATING,
      required: true,
      section: "performance-criteria",
      order: 1,
      width: "half",
      helpText: "Rate the supplier's adherence to delivery schedules",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Timeliness rating is required",
        },
      ],
    },
    {
      id: "communication",
      name: "communication",
      label: "Communication",
      type: FieldType.RATING,
      required: true,
      section: "performance-criteria",
      order: 2,
      width: "half",
      helpText: "Rate the supplier's communication effectiveness",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Communication rating is required",
        },
      ],
    },
    {
      id: "responsiveness",
      name: "responsiveness",
      label: "Responsiveness",
      type: FieldType.RATING,
      required: true,
      section: "performance-criteria",
      order: 3,
      width: "half",
      helpText: "Rate the supplier's responsiveness to requests and issues",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Responsiveness rating is required",
        },
      ],
    },
    {
      id: "price-competitiveness",
      name: "priceCompetitiveness",
      label: "Price Competitiveness",
      type: FieldType.RATING,
      required: true,
      section: "performance-criteria",
      order: 4,
      width: "half",
      helpText: "Rate the supplier's price competitiveness",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Price competitiveness rating is required",
        },
      ],
    },
    {
      id: "flexibility",
      name: "flexibility",
      label: "Flexibility",
      type: FieldType.RATING,
      required: true,
      section: "performance-criteria",
      order: 5,
      width: "half",
      helpText: "Rate the supplier's flexibility to accommodate changes",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Flexibility rating is required",
        },
      ],
    },
    {
      id: "documentation-accuracy",
      name: "documentationAccuracy",
      label: "Documentation Accuracy",
      type: FieldType.RATING,
      required: true,
      section: "performance-criteria",
      order: 6,
      width: "half",
      helpText: "Rate the accuracy of supplier's documentation",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Documentation accuracy rating is required",
        },
      ],
    },
    {
      id: "product-quality",
      name: "productQuality",
      label: "Product/Service Quality",
      type: FieldType.RATING,
      required: true,
      section: "quality-assessment",
      order: 1,
      width: "half",
      helpText: "Rate the overall quality of products or services",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Product/service quality rating is required",
        },
      ],
    },
    {
      id: "consistency",
      name: "consistency",
      label: "Consistency",
      type: FieldType.RATING,
      required: true,
      section: "quality-assessment",
      order: 2,
      width: "half",
      helpText: "Rate the consistency of product/service quality",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Consistency rating is required",
        },
      ],
    },
    {
      id: "specification-compliance",
      name: "specificationCompliance",
      label: "Specification Compliance",
      type: FieldType.SELECT,
      required: true,
      section: "quality-assessment",
      order: 3,
      width: "half",
      options: [
        { value: "excellent", label: "Excellent" },
        { value: "good", label: "Good" },
        { value: "satisfactory", label: "Satisfactory" },
        { value: "poor", label: "Poor" },
        { value: "unacceptable", label: "Unacceptable" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Specification compliance assessment is required",
        },
      ],
    },
    {
      id: "defects-rate",
      name: "defectsRate",
      label: "Defects Rate",
      type: FieldType.SELECT,
      required: true,
      section: "quality-assessment",
      order: 4,
      width: "half",
      options: [
        { value: "none", label: "None" },
        { value: "very-low", label: "Very Low (< 1%)" },
        { value: "low", label: "Low (1-3%)" },
        { value: "moderate", label: "Moderate (3-5%)" },
        { value: "high", label: "High (5-10%)" },
        { value: "very-high", label: "Very High (> 10%)" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Defects rate assessment is required",
        },
      ],
    },
    {
      id: "quality-issues",
      name: "qualityIssues",
      label: "Quality Issues",
      type: FieldType.TEXTAREA,
      required: false,
      section: "quality-assessment",
      order: 5,
      width: "full",
      placeholder: "Describe any quality issues encountered",
    },
    {
      id: "on-time-delivery",
      name: "onTimeDelivery",
      label: "On-Time Delivery Rate",
      type: FieldType.SELECT,
      required: true,
      section: "delivery-assessment",
      order: 1,
      width: "half",
      options: [
        { value: "excellent", label: "Excellent (> 95%)" },
        { value: "good", label: "Good (90-95%)" },
        { value: "satisfactory", label: "Satisfactory (80-90%)" },
        { value: "poor", label: "Poor (70-80%)" },
        { value: "unacceptable", label: "Unacceptable (< 70%)" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "On-time delivery assessment is required",
        },
      ],
    },
    {
      id: "order-accuracy",
      name: "orderAccuracy",
      label: "Order Accuracy",
      type: FieldType.SELECT,
      required: true,
      section: "delivery-assessment",
      order: 2,
      width: "half",
      options: [
        { value: "excellent", label: "Excellent (> 95%)" },
        { value: "good", label: "Good (90-95%)" },
        { value: "satisfactory", label: "Satisfactory (80-90%)" },
        { value: "poor", label: "Poor (70-80%)" },
        { value: "unacceptable", label: "Unacceptable (< 70%)" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Order accuracy assessment is required",
        },
      ],
    },
    {
      id: "delivery-issues",
      name: "deliveryIssues",
      label: "Delivery Issues",
      type: FieldType.TEXTAREA,
      required: false,
      section: "delivery-assessment",
      order: 3,
      width: "full",
      placeholder: "Describe any delivery issues encountered",
    },
    {
      id: "average-delay",
      name: "averageDelay",
      label: "Average Delay (Days)",
      type: FieldType.NUMBER,
      required: false,
      section: "delivery-assessment",
      order: 4,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.MIN,
          value: 0,
          message: "Average delay must be 0 or greater",
        },
      ],
    },
    {
      id: "overall-rating",
      name: "overallRating",
      label: "Overall Rating",
      type: FieldType.RATING,
      required: true,
      section: "overall-evaluation",
      order: 1,
      width: "half",
      helpText: "Overall performance rating for the supplier",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Overall rating is required",
        },
      ],
    },
    {
      id: "recommend-future",
      name: "recommendFuture",
      label: "Recommend for Future Business",
      type: FieldType.SELECT,
      required: true,
      section: "overall-evaluation",
      order: 2,
      width: "half",
      options: [
        { value: "highly", label: "Highly Recommend" },
        { value: "recommend", label: "Recommend" },
        { value: "conditional", label: "Recommend with Conditions" },
        { value: "not", label: "Do Not Recommend" },
      ],
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Future recommendation is required",
        },
      ],
    },
    {
      id: "strengths",
      name: "strengths",
      label: "Supplier Strengths",
      type: FieldType.TEXTAREA,
      required: true,
      section: "overall-evaluation",
      order: 3,
      width: "full",
      placeholder: "List the supplier's key strengths",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Supplier strengths are required",
        },
      ],
    },
    {
      id: "areas-for-improvement",
      name: "areasForImprovement",
      label: "Areas for Improvement",
      type: FieldType.TEXTAREA,
      required: true,
      section: "overall-evaluation",
      order: 4,
      width: "full",
      placeholder: "List areas where the supplier could improve",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Areas for improvement are required",
        },
      ],
    },
    {
      id: "action-plan",
      name: "actionPlan",
      label: "Action Plan",
      type: FieldType.TEXTAREA,
      required: false,
      section: "overall-evaluation",
      order: 5,
      width: "full",
      placeholder:
        "Describe any action plan for addressing issues with this supplier",
    },
    {
      id: "supporting-documents",
      name: "supportingDocuments",
      label: "Supporting Documents",
      type: FieldType.FILE,
      required: false,
      section: "documentation",
      order: 1,
      width: "full",
      helpText:
        "Upload any supporting documents (delivery records, quality reports, etc.)",
      multiple: true,
    },
    {
      id: "evaluator-signature",
      name: "evaluatorSignature",
      label: "Evaluator Signature",
      type: FieldType.SIGNATURE,
      required: true,
      section: "documentation",
      order: 2,
      width: "half",
      validation: [
        {
          type: ValidationRuleType.REQUIRED,
          message: "Evaluator signature is required",
        },
      ],
    },
    {
      id: "manager-signature",
      name: "managerSignature",
      label: "Manager Signature",
      type: FieldType.SIGNATURE,
      required: false,
      section: "documentation",
      order: 3,
      width: "half",
    },
    {
      id: "evaluation-status",
      name: "evaluationStatus",
      label: "Evaluation Status",
      type: FieldType.HIDDEN,
      required: false,
      section: "documentation",
      order: 4,
      width: "full",
      defaultValue: "Completed",
    },
  ],
  dependencies: [],
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

// Register forms with the form registry
formRegistry.registerForm(
  {
    id: supplierPerformance.id,
    title: supplierPerformance.title,
    description: supplierPerformance.description,
    module: FormModule.SUPPLIER,
    clientTypes: supplierPerformance.clientTypes,
    permissions: supplierPerformance.permissions,
    dependencies: supplierPerformance.dependencies,
    version: supplierPerformance.version,
    path: "/supplier/performance",
    icon: "clipboard-check",
    isActive: true,
  },
  supplierPerformance,
);
