// This is the service worker file that will be used by VitePWA
// It will be processed during build time

import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { NetworkFirst } from "workbox-strategies";

// Precache all assets generated by your build process
precacheAndRoute(self.__WB_MANIFEST);

// Custom API caching strategy
registerRoute(
  ({ url }) => url.origin === "https://api.barakatna.com",
  new NetworkFirst({
    cacheName: "api-cache",
    networkTimeoutSeconds: 10,
  }),
);

// This allows the service worker to be updated immediately when a new version is available
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
